---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-actions-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgCKS/0LIwGgQgfftP9dl9LKqIhRBRxZC1aSE7NMQI9Ip8cv+QndNX1bkcdXIhZPpjP81J6wBsN4kxm2h+yCq8sZeII+YeZFHiMI/fh80ljityGWWCnfwht1XLv9XQPxsRzDa9LNI+nyGwie9uBvPke0Y9YhOAiUWshUdxKV+pK0ODVCasFy4FkhC1z2HUg16aqT5LooAdWCbUoTLVxP6euZ4AlBofyBpDKhmBu2Q+cOUeaTiAZLRS5LsXNc37wKmbixW/1eBsIUybcbOZNpTM12lxBEHGl1pR8ixc3Svn6hEAFd5L9ATMme5Of9602pDN4ilauJ+GHwWTb5ZnyNT0H3t5t1a1+ccDd9PAe2B4XviwCUVMYY0xEs3HISZI3rfzEE7iYJdP0lE2HLnP6EMbLcjUf84awEAZni2iwTXfz73sINgZw4RC9WNc7LDMewMTy+Ql3b46GVTUWvSKtg46HOLP3PQHNfZbAJSHIral+VWWIcJ4apbK5JdHGKGbv/bhY2tsZ5GgQ6O5TPELX+or5gRH3u5opEuH85ofRV+XN8C/aY8eNe3Ke7N2RYm65cWp/rk7AczpqKdN32hszAMpDN0i54xvFMy+VMRjtZiPZvAO0uAvnk5QEgJrcL7WH+Xg/0NaNis58wSHLtllLVS5WXQhcp/50YQENDRjH3rlVa+zT3xsU8i/nkXRbItRo75o04yKtuhFREdvgem6/SDXoI/96WFbSGeENaAAm51MhG607IHorQTCh8
  template:
    metadata:
      name: gitea-actions-secret
      namespace: gitea
