---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-actions-secret
  namespace: default
spec:
  encryptedData:
    token: AgDBNVK4Lc4SxyH0ZI3uJ9W2q/HMsnbExkEZTskOUH/gMDKtbCPM+puKYD+JPkNohNvF1YeDNxU3r0fGKAbV23mUDkmtChSstA51B/3MYuL3dNde914VysYskcouOrmrFxQILciE3MHbZR6IIMV1ZKNXEDZxyjac1790th1f9qtK7Pdz2tnTbnCpSGZy3LO7aVHuOttfPal61gLyYRV1XWecGli5qxx2XJwWReDzrgD94icq6jz/GbhP54mYaIkGgrm09m9KMvFB4LcI9hGfC2ynyvzmeoU8BP8Bv0TpQrwYQRmyLozbck37j1y+g/Wru6foHPFNeE9TZL0C0Cs5I26xMn2NrKCEIQuooZ9lLu8JI3Yet9B7D0olaifnKjqDTVkVPzTAXijSVN/+OdPWxeXA8MUH7w8TwU6z4HegesEdYYnhbj+qXSzZz6ftVjjKODKbwe4ra8J2b57YkKp1EGhCNdIDMnKfek5pQlLzEY/BDKUR1UeZQvCrTNdIcsynZHLClqfSYXFFQkvc49jOIeLx415zk/Tiw0OFOJjJFBudxjfyWHadg6TkkBJrwJVngt6b2Z9iHc/lPDI+ThCnq3EAYSCyBY/Lp9rWVYAFmtd3JEQf4N0iLkR6voe0lbwCImWHRdf5NxHwDBZc4di1eNljQXuz0qYMk7C1yOyGcvpJJBsMXSC+IbgCA3DZx2qc5fp4iHibqY2otXDhcbWD11IIqzF+AjprFRd/XPEsgq48q+w29ru98udW
  template:
    metadata:
      name: gitea-actions-secret
      namespace: default
