apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: "1.5.3"
    helm:
      releaseName: longhorn
      values: |
        defaultSettings:
          backupTarget: "nfs://192.168.11.55:/volume1/longhorn-backup"
          defaultDataPath: "/mnt/longhorn"
          defaultReplicaCount: 3
        
        persistence:
          defaultClass: true
        
        preUpgradeChecker:
          jobEnabled: false
        
        # Ingress Configuration
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.reckeweg.io
          tls: true
          tlsSecret: longhorn-tls
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
