apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-distributor
  namespace: cert-distribution
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-distributor-read-wildcard-secret
  namespace: cert-distribution
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["wildcard-reckeweg-io-tls"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-distributor-read-wildcard-secret
  namespace: cert-distribution
subjects:
  - kind: ServiceAccount
    name: cert-distributor
    namespace: cert-distribution
roleRef:
  kind: Role
  name: cert-distributor-read-wildcard-secret
  apiGroup: rbac.authorization.k8s.io
