---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-distributor-dsm-credentials
  namespace: cert-distribution
spec:
  encryptedData:
    dsm-password: AgCTCeGM6mJd25Ftgzf9e2lKv6DWBiJ5W4Q3d83J+mxB08JiWeooLlFMdh20PiI6zI5BfTXxoDAoqjjCYDsg6Qe+5j0O/k2lYLUvAsG/21Gb6kLOlT9mXgqS8yO2av2Z//dyAPbTY9Fv5lJQruOEeYu8we21B9FrE6kKpWxizJG8EzdymySXJ+OVUtwi9ijJZWsfpEzq0+zzPODXnK0FTTrZqqt8zEWd8Yl7RMp53N0ZJmnx6Pu9seLIwBW+axKIHnKNzxdTJqxGW35APz9g7zdWG9Bt7QJ4PRlcTkjo2e9MN+kXMFy/NIJiUCdNTC5rVtGfhNFfo0YLLsts7XH/6Oa/StSDZESLvAVPiRAGpORMhgr4gj4uS/s210vbhZo6QiWResjqwqSGZtiPQxY6PF4puf1GrsRNqpn2mF4UZhmOZEBXjoYKtlq3mILM9qnF4JjLY7OSDs3O3W7JEqLoU7ZoIPHhzZ+DWLsx+vQ6SaIUJYKkiU5Pc7oFKdZeYpw24Az5RKCm4XbDJp2bFPRLFnItJfboD8kcsgNMC1d46ql1jX/L9fCbhlj7ZaQGR9Z5spmHDHfxPR3sPIb84DzQ7156z2yz+RDq699FHzDInOEDMQ23Y7jbiAbZqFc6NE0rlkoW9j6FyoTxmjrfz9JOR6HjvfOsvaljvut/l4nld/8BB4hVjKAi9f5figinOaLkd7UEM8OHx/0=
    dsm-user: AgBOY4g9demsAFWMh42AXge1GiPjz6QDqlLQRJKJYbVeikdvFDn3OkQT1uhCu3SvaJieYKwf3HqEYzQjCJHYIfsX53ETh6g4sZg7TDRN0A+fq/b5+F4S6igMAO2v0G2HD3Y7/5puh+okaw+xU+2w4XXW374F5nNNsUecbIQfnWY9J0wdaEw74MBLUpMYPoDqQI6UAOa2jbdkVKMpRpmL+mUKyPhRxGEfzeHYz3AIZRmmxfeMCRSw5I30FF3bmWCywQNUIOpa2x6OBaZA0dSM5UeuE4M6HvGIxohLaOzpWS9Ry45+C17x7k4GBMuW624gfg2/p3C4YMd7F8FUYH2Cjsq+IcpRVy/KIYlWwmuYaMFHT5MIXgy5xMdI8VvoBFTovW8pnM2LCV7OBclnBX0y/cN/wo6OMvqWCfMocCTNL62yB1n5a0CRyvYzoOlziE5nYOniFS8fHJQsCg/TcOwnB/0ntDgSJqyt67s8ERyFs5J/+6zZYjHVt7Z8opTp1yWs77M5tGpCp11gV8aW7m/TTt7V1Z9XUMgDOeH417h8fpFFZBx1bGVYN8RLn7NeMMVt8hQP+oRMHnoD7vMa9GIvtzurKHXqKyiYF36tLWxSjHZg0WscHS6JQ03nX25Dj/KckjmkZjJGvP7oqCpHJM2xjnhkFu7AfCG4V54cSvQ9a/JEhzbUDeCX+zUeJqSesP/ecovjNMC6MN0YFrgMcWO0vrC3
  template:
    metadata:
      name: cert-distributor-dsm-credentials
      namespace: cert-distribution
    type: Opaque
