---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-distributor-dsm-credentials
  namespace: cert-distribution
spec:
  encryptedData:
    dsm-password: AgBBouLsSlWdD3haJcZbqaaP9mP+yVvsj4K0n6en0RAXxecSeGkItII8imdUvcVoxD7vPYDk6uv+PuSFazbHUQ2VjdgSy2n23ex7Lw9q7jaQAorBd2VNpmVDu52NP7YwywdWZ8PySBCw1EOIT6NFuNcnkR5zifWcwKs3PQvcRaWK4mdGN6V3YtAuKoaWqUr4JN2TJJXxt2hgCD5exwEMneQ/QrbpyHBmgiIKV0aCU/12UM7lBtXkwPoN0iOcBvX7f1X9v7X4Hn+HcxOh/Pl06euoc2UE6+ERJBIyKbCn1aN8urRmMkM+VWfWVX2HMiNPdJ8cSCWDTzGYXIrQ6YlmxqYuYPdNuCC608LV/AaTfknupr/bei1oUsi9uZL3qchIULuLom9j7N8Yfx1rS8QTBj0ihiHb2snSm+hwnOpVjYyQ5u330eja4nfDVQxmeEAhqXMoRNgt9rUdqUwhLQpXQfmK7A7o8RUoAXCCSHg1y1fmmE5jpVF82+KslJiyttL9BsHDcPtCIrys5ngen3Y8V6blplxyOzObrNVOMMfXdiWmbAfM5SCH97HU1ouNkfA4ea057Yy/tYhmH4laRvKPGYMBN1R7noUDMJKPInxWIpTAqRNL9B/xCJ6DYNnD0CGfOs4ZwChFvjBGl/uWCcvhv0lRywjWkSHrzTn/1OV54F8u8FpLsClgux4r2a2m7vOUy2r2BoR1cqc=
    dsm-user: AgBY/7x+UWTsTbzOgJeRoCz1v0/OgQn1fphI+h9B0nqc/llfRZXhlrBRPhy/ckzQbc8fhoIcWEnxiGqqMFQZXrdqJrZqKgryyEP+06DralHNvOirSn3KaC/MVA4mc/TAUGOVrpV096NaMBzJXoQyNX5MuFoPjBROqJn2sPiz/n8E0AzlQ2jsPXZfvFfhU+ZRH/EgGTP4mkdyIWgkBZn8zUi7HrY5mY7jeehGspwifCrEMkRiWPLoHHFUQy+prVeQ0YFrhcNAg3wzwo4ieol4ZS3Ng4GhhTz8qmZQyykNlqfVtUgdz1vykmfFX6DbObmQu5kE8mwta2e22Pv8MzuqsFdMHNn37I54t6I6asz7TgD09tLZG21YWw3aJP48I27liODhdPTxaA51f6PKBekVWwQdDx9hKP9mo4ioJfhRyAmFCMZ/WUM+VkhOLEdZuu2sx19kKljDYb3VhXNp/OuFkCztQvtAouO0kgu3rmEJW83mqmOvGegFnaoJymEolNFvdFwpbICD/7oxrp1M2zIrmhGFBpdQTOW4VUWxiUb2DhmVhMKHPIseceL01PEGAbR8bTrYM32ZnJejNJohjlOjVz/oLsMr6aX1BrQgs8P7KwM1z+4XirorKcw0gbKNNncYBgm9YzIIIWeB5megtf0KJG9IuNlBKt1Z2ozHDriOGN7jteUrFOfjtfG08BvvjTHyBXmEj6m+nEmpjCtKf5TDxa7w
  template:
    metadata:
      name: cert-distributor-dsm-credentials
      namespace: cert-distribution
