---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-distributor-ssh-key
  namespace: cert-distribution
spec:
  encryptedData:
    ssh-privatekey: AgCk7vdQW3gqoP5xr14vi7ixE7KFDmtxQP5jRJttUhM2C1Y3Qya7LT6HJ9tHDf8dLyqvxwAxz+e4+Qz0lToCbFJUrrBaATS4NeQOD3e4CtREiHcLO7p2j08ZLUiY0pGSbqBIrHVY8vUeUC/KKsD/xK54y2+4+Zq5Bomf0h1rs3fwfIS9JFBuScMGkX3LubcQrtL5zazMETz36mj/QAbpFPaIIHH9KvCeYL6gqF1wBmUC15xru2yJur7IBFtDnVh24IwPaCfibcQLt/02KdKt8MlTQr1rQQvttYrZA3XdHoljOxpKkpYr+HTFfQoG9rMnws5eBLXupf6fiyfiB4+L1sTLcM8Y/rJWJoY1vymePaywZHdm1NhajWEySfo0NHQ9InlGCEAJhAfWjiWGLQal0fbnoVaRgJ+uFsUZyRRRwhrhshqDxLDyxWUJFZQPhF+vtTC5j17Kn7XqQVyChcoa8v9GUwdDzidN4PCyRLcb+tN/R9XwGa0Cp6bamq4nuQcza33ay8Uw/ItWntXxAxRCuOXoQ0+nj6uwi47b2M6NvKIEWfdEB4BNmqQ1Ayjsk5BZMp7J1KuBWdzgY+qOyr786nJuzYhO1QmERx1w1fypZXyndF7dHN2OSIF+sfhZ9WB68igAFkVsdof8TZsO/eAk/drSiELybbKMhOjNc3XgiexOq0WDdB9SsH8ZuUPBuCz5TOWYiH7kNBpVavPisL8KUJR4wOeyYF+MGGoLRNQxO5mMK1U5P1SIUDZ8eJ/8goom2HMs0LMQS2L0EVErGAbwnYv8KyafbjcHPlVO5X5w9rkpSB570abQoNz1yzejHZqMSIwq5Xn4qfbOQx0ihXTyB8b5rSPNolZp3pCNbW3hC6+pPa6ghopuYVS5oP372yVmrH52l8Ze/xHtTBnEJJHLOewmdvN5Y5JZk54pjqapHG1D5rcej+UaLGsHgwOMHTSu61yr8X0GOmLBzI8qhFvu8SphZaP5VIBWXa0vJC3yIOv9PinGNbhlnFkDma/65Pzj32sQGeKsvlBwX/aCqP8IDSBfNkhRuKMu1c6RGlwGzcwZKRtHFl1KSFQ6y6mQSi5wzrXIOLJOzhOCf5HItA/QLp0SVlIxG8zajfGjdnas3eB9s6VodA8PtVkKUqj3uLa9PQUtgeNEHjdBYiT6/X6qcdVxLVGtqQ2aVfNLgI2GgGIiPw3HjAL3yw/jYHhvYiwsELGBtwiII1KtRT/5rVbY9Shntfm0NXF7PWTns42safk8ANnbZzTLlQTzQ4aGGgCk/Utr8jYCP+/36WPDfgs=
  template:
    metadata:
      name: cert-distributor-ssh-key
      namespace: cert-distribution
    type: kubernetes.io/ssh-auth
