---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-distributor-dsm-credentials
  namespace: cert-distribution
spec:
  encryptedData:
    dsm-password: AgBrHFyMtFSwjix79zgvfXRUFcOI4au1OrKFmNvXEsDQjBKmP2VaMaKLzWrLUvMtPcpCUYLhNIct+b9Mu5oKrr3d+jsrttD7CjJ133r8BL6DUPJHoGLgIVRmWhqRXFOAMQJkyb9CTuPdrB9ktJukqkCdy4cQ/WC55XsHjEy1cnTVOM+xh1USLgOxuocfYnEPQN+NKvmvDNpiup49VOQX0OPVgPH4fxMQ4+mXAyN0+MX6/2XaYT1MqNN0TDXDJLKVPoGRuF8pZwJMxyYnV+3MXAUordv+X5vvw2BRzLxZL2om19fCacmjIa/cTOc1g6G0onm9s3DWDEwCSSmCxx5+hHi+QN3z1gOlD5dZIlKNUhDPi6HXzEVL8lT1cY73w/rpENd9l+vxi0ybDlnLDN09ZusiE98lqCirm7Yga8UughJT2pGKnqU3eqwBNehpkvFkMdzc0DEOh/oG+T68tDW25KzsTh0zb15jB+wKID6hvPUslk6ncC9C3Pwa2PvKlN0GmtPdhDm99OCmtmWx65tmkgH3GIB5u49BmHT5OIwxu9XdbefMpVAdWbwjAFSnWJsnHTIO3UM+c/Glf9vE2gAF9uygjfWlC7M/XW4mD6bBwCpIqpXy+RhH31LoqTTuHDH1usUtvG7STGT4Pi/hupgiGo6hXkWt2WPiI6OElrWFs5MvsxtyZ9NRFHrgKXklcP35jWQkttsfPfk=
    dsm-user: AgBVIT+RHJfBxacy6wgDIizcL+2A/aPsrwObjQf+gXckwpo5Gfqpnqbkth3ryGJAeFWVmJsK3RW3YSJifMgw21mP8Mm0SdAuwo2TLWLFftIPVIsV5tH2koVZyYtEbHWEmzoytrVcCrKuIXBUJToiL44CpL14TOJUBA2amMLIDddq4pc3Ftfnqq/UIhyaOD5yBNAyK87gkAkTvmc6k60F9H4uIyosuJlDBGvtCgrUSFOoUIbw+FoSRYCKbTIXFfvObjlz72+DabOB0nV8X3debWOtBd3LbBURgtnrUzy0FvOgtsIuVSrqV/AjE1LdTTJmhrjx7bIeIFNAQFwVMUp52nto7CARHBopXHIc7ynim0ntlPnb7Wg0bU/GSmjt0ddJYHLM4ssWTLBB5/nDVGq+Bj/3W5NgKNmulKovQ61o87PVFnShuRZLZC2K/fFBwhkfIyKpzhy8CgiZCbD6xW4a+swR0cVVbYW+4b+jv+sD2mYqR7ybM2OcZyhvDVJFNEP6GVJMf/10uyImlaOz1JbVsmmZ/ktMFQ6KZFiGSOzcWGT6EJFsU5yUMmzP03FbG2IoTLMekPU+/qlokuJ63dvTKVvPa48ofXzX2sFTlK72TfesNIrVFCAScS72eZN/PDi+9R8SaIiM3BnfAaL53r6/ptlXRjp+MOSZ58vgw72jI0UCDY7Mzmy1KqAT//ebRptkEhmDFf+F7KLGVxbNdUlf4JPA
  template:
    metadata:
      name: cert-distributor-dsm-credentials
      namespace: cert-distribution
    type: Opaque
