apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-alertmanager-credentials.yaml
  - sealed-grafana-admin-secret.yaml
  - homelab-version-checker-v2.yaml
  - loki-datasource-configmap.yaml
