---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgCGduBpzC7V7HRmbY62nAd05AQyLI4horrgBslmaqXw5phje84t+aDQEILjBCaL6ckvuoqinOEL+QCnurxpP9WwZ6ctR88/kJBi80CxIpZYXmG+nP0IdJDq9pimEoekeCgEJpR15RLdU6WD2OFL+au7NW1fJcwkUuT5pigdnZcbQPn3G1GU4uYCX0p/BIXq4DAN3ETMF7UB2PwVxjWqrCu5GWNg4msf2Kpny7hxDHWrZLtArPSG3VlAhTryKKDKCWSTt4Hv/PtiGLHJcgikbbEApnx8wcLVbggrcJ9n9IMBrfCeuxCvcp8mZe+nAdx7w2QvlZYmttV+64NALwQO1WrpAdh2HnSljJxiyFCcyd9grzwwmEPl7u/eKnnzoq6GLxCtctvuhNlQ5TyODqIlOX/tmOE3LcdQcvc7/Tm0y6gMdMhb69tt8JE2X4epQ2T39PWqDo5Y3cJExvo/xHRf3X/4QcoC9PrsF+HFPFjb2F2tF1T59HN/Bjm3JBQ8WFk3yiY0BCa6xP2dJ172VwZ1mequitO+a1KKAIK4okCY/dImV29/HrqymW4l5MPaztIEaM+hNnvak9r3CbxGm2uLry4VB4q9NeV2aztUMT81Pa6IBJu+euoDNFpOO514w3LyKibwbHazgqs4S7RkJG+zAm68dmuP8k4baaey/wQwZc0sbshEJ6C6TrSLwSvSoefBUttnF76cWp6D31oL9tG7EOiQOuGRBPhdugOVK5fn3jITQZ0Ls6YGpX8PNairTuFBE178oN6aXXum8XUR9a7DqC2G
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
