---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCA/1/8ytRS9kDkXlA+XV9ZQLYAb6xCjPj91sD5qaCmBZanzNhOTjbattXclP3OffssUpCvGL9XCuDiRcXMMgz1c5UpOez+JsKoZNEUTQquRuzWXDwCNAEGMVdyAVwyo/+9l2zGsilhTVs/9mIWil4nhjQ4j1WCijBldqoWuQxcPa0xX58hjjbrcykP9kol1mMCJK27O1lNk1spBaIhGuPE+L0XUGB1sG5zqqD5BP+/dcQ/RD9ji5Jv9M+97VRlO+daXAeYlmQ4o9bEp6oEVljHwmyfMtkd4BRBuc7oPdccZi8wE1pVOrgaUi1DwM2eWo0Xrwa8OOBBfxgsw5vBnwG2GwCpa7qs03+1AxuOo/VtQzfycho6az+4cN52slZu6xOzUEQAZe7EzNSUP7iQkVqyFV4LBzQLSlyX5Zl5vCe4GnspFC1zFb3p35rpsLhi4hNspWQQq6SwmH01UB54Nr8Q3H++n1FH4LB0iDWeEmtXERniCjJHhT/axaehPwqDSXfnkG1cgvBKyQu2uAWjtVzTq8k8AK3OWS4C/7LrcuMj+wLOmLn9OBCOXxubnruf2pWQzXfCW74IMAl4MFZaA9DQ8uBPqlKG+LEIgSaz0wTbhiTvNoXSN2JQ4qWVhSjW3O7e4tNqdUaWFdwrdjeqRsL2MmNUDxq9b8xD2jYVRmIqWRijdGRaueV94Y5nlJFaJ/N3OXnK9HGO+X9lYnBoY2AdJdgfuA==
    admin-user: AgAji2ENnh2NQVHtdDGDNLmRPSRfCGVQkgXfk8kQ+Zfg1+1Vu9EeRFE9fNo5ZWCase8tIHL0swlSGsXF32tADxCZmyG0GMtV0xJVjyZ9SZMfoWC6vWkBMjP1bQ1GIaS3b0qm/rBPCq5eFMtHpQ7D+WPcoPwakZ0u3eqxodGEClxn6K1i7FhfFU7MH1h2oE49MsHr2msqVJ4UkA5VNz2kTQhjnEoHcgR2JF07JMZD097xs7b5cBm4POLGmsy4utiSGYBZyMJ8qsFPJfhyLGQjuktddD4IRnuM8491cV72V04cB3vh/XR/uAuHSl3lPvl539doCPoAV58L538WE5+vSXNzmZczv3mvNkmk6UCbMUsSNIXchqfhtoCKVtTyDVSaHwn30PqZBDiUBfjhc9djr6LkWEuUu9G4A2gY+YHSKPurircAWF9khdYCORsfXGczeOdonUjdvYr906xMvrgJifbMdvOzMa6rfKUI9FfAt19iicZevdLbbc9x6ta6MB+0oQSuDj/N7O14OsXkj+NJWhY7A1Cr2pqN55YpKUAANzx19FppyD3xHVuY8U5A7dkVBHmcRB/EVYv/A3X0c6vnXU3EmlHIbS34GEGKzIBAtc3UfekhrXHIHq3ULRCpGV2MgZ/H4vYLo6FWKb4jiC742daPSNjRZrTIvk9WhE6MK2dLehelPm5j+F1comQrIvfQtTiO4gU4og==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
