---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCMukz+VACqqZ1Mg9AainER4x3n3T1AhIoQqfGV++qhJ+DEk7gaTosPz0IndOrCukWjyShv/fK6eYeT40RE1WRkb08helpCE3A3IrKPX/xwMydpT7CcI4q2pGGcS/EhJylUdD8AqHsIYTxUsOZJHYIlJZ8rEEkQTzrknF+PSKuoV/WqdlNBzp04u7V8sgUgpBCJVqtNMQp+bPymM1bqUkfIstkVEgQSeo/LEDR6QAIIwPUCQhZrYp5U9EghDgB/pKZ0oMfBMDP+83D9xjv0f+U7kcLNeJGJ/EV37Z6K9PXbd3Hmg8J7Fd56ouB2lLi2TPhvCVcGpeErV1YDRbXeE9n6eqtOUriloc+mm4jOawHhCMk1e1oUwD29Um2k3ku/UMvIhZgZf8KPNVxVqtq0EumCYbOUtab1hPUT8C49K3vo9fWWVoklaT4o1HrAlojLBVD7GD61rz37g/X3VZKogDtOYPkRHlpTFuNmMLhhg9bw5qmFICZQS1ziUHbwf+xN5rbBAknuUAWCf6eHqtEn2+tlDfCF8IRjyxMSAxtVWvqH1das2j0YSFQoxZ15TStLQh+MngFQMg6YUpCbaPREyzzqnL/3aCPTdad4UWKH4Onxdy/V+G2F6usB4Zp3YKcEtf42XI5JIUZ6JtzrWmMSShis0kyEfTKZI4L9S0V/rjTl6cAbkuOt4gArzYPI3KaNexS4DECCBNnfhrvY1WCvlLTksxwQvg==
    admin-user: AgAMX6vCSBZxTtCt1OK6vJRm9eHDozZsK2Pn23zqawdUkZzcP6ojNg7nXEZJ2TQNYzJDyC2WNDV7x/q+Pu2Ynm2WORsk55jA7HtDOBAVz8Fv+fRb3ZblidR03wGpuWw/Llaxt4g5ANeQdgw14aO5pxdjHy4jFzfgBBHXTwU8JWoCffOHb9a2gls39cJ1wIpyWM3dyyXWH7+ke3k9EA0E70M8dWmuMxu51S3vHKLYr75FvQRr37Hki/YJtFLIcnk8uDQ2LAEmUNWQ5v0ViJmPBaKQO6NPs/TjtYstmLXWbSJvHGJyCP9rgZ3y9cBzZx7obxpziK3WiwNWlXtwKlKMYh3mz6/I/svXLjjChxo2L5XJ4Pj7Li5y1ufySAUWr/EBLYG8MaqEQeuSoryy7rn3fzxEyoQ2nkjdVKqShmtC4qwgJs27+p+6q7+sFaf0djRDpRRX3+ynzir4GioTg5mvuo8s8l82I7RjLvrt59J6xup41c5QvOlKc/9GrfX5sqARyJqupYxQ0K1ug2E4bVuPoK2wzTVCA6UjPPEOEKa6UadlI1lEq8UXrPOMFyjy0mT4WJOzI3bHa+Wquv0p4jpTWBMRDnctDQUTCAJ7oWiQRV5asyr1N8HoRSoiFTKIA7Ibom6PQRoPpe0MJNA1MgDQP+uOueHzwvoiuO5VJF21tGRHaeKD+ikQ3W/xtzmNyPrYbsVXc2hNhA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
