---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCW623vMF3HtVd5R/UISEjIVSWfsty48KT+hNjspGilk2vA8OSmnF4mAoy05jOAmGY6UB/1cZ60lnbNv4dGy7TXmqBeVjy8RQEI5/oAAgvdNlYWnRNHTmnTZjYkee9etNndxmr6KRTAfXxq1SXSjS290e1Y2DL/Qz/q1dcqcTsRM4qBWuQufzFmL5FJ+VsyONr1LRXTTGriC+/0EG0PE0vg0s1YBQ2z3MFodevvuyaNxc2xL52PlwYFb2ov8HJM9WWKQT+DaNWD4+2Gf4nBoYRhNA//71pCDCCyd2bHKfTkLizCCrspwUtjXq5yr0QFTaTRSx72jUMWCMqKOFSHHkzpxrr5kEwY5mLcvFVRwQNRKCc386KF9cuaL/TY3mY6vbvNyGL9IhiwpvykrLeb1+KLt1HqY0g6MOoUVE6bu+laY03gc9RbMB1rNHKu2H6uKvGQk7tMIbtZCI+XKF+2pg27BTBQPQzUfOzjG8Oy9GPB410gSZcdb1FikU8iiZxd22qJd/N1qdP1o1w+GkkmGwx564vAQO/ZlxvqB3h7F6ufPJZnkrnNyKLc6oWJUBAZrUDdBnMVqECZeZ4L1HqiMUlcrnzDvhkdcdxYlYMNj3r7RDjAcdpYuUOcTL6W1pLfa0eZ7GLycwXlu78P+SqXAMe+7t5GmV9WLBpr7iLDyUzOk49NGDn0ocZSB8GQHfP3HCOINERD8hBghDDXFRL2KQb44W+g+g==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
