---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgAdczJGFTO9xxV41JdTzfppd7QfjesTZHaqx+0HwWICMe2C9z6YbsoVYAky0oYHnSNYBGtM5T4UqlceGJtieFYe/9FimP1yvIAyvRG3Jhm9YdSwuaC0140OIINIzy+kjjpxFhJGeSXy5W0YKur4KepUpI5+QcTgBYEk32lT1PUfQlgo2s297HCVvaI9D4lirDyQhGEkHKr0VKslEe6p9WyGnk08jLltyUQOgp9zF49JAQyLIX+aWgXFlMOMur3trcU+2Sb6nrbqQSMfD6944jE13A/2pdykwUaJzBQuc8JDFZWMpafBjlhV3RWkdYnep1sR2Ibwty2Sf2rUSXKafLmwX7Lz1fCiB0CLykmEvz9is3572cu9p7yHLN2GYDbK3OhoNA35sxp6Il/DyFF+boTED0S5S+jOKEIeM/j0pJ7/a3FaAU2Q1o1ZdSGQsHbirJ46beJB2U1AdVH6k19uXoS0iz287IKspkacL23z5ikYPctrwfrIN2G2fLT0CXj8kAE3ny2ItFOiZYRvGsqZqOITn24ezGc4Rq0/mCD0pX+9h1TMiucppqq2SRrU4q0bRupQnSa0eleYbjrQM2MdqE0GuLtwp97BFfbjLBj7IfVVt57XefOmXhrN8po1x8DPV9E96JeoOYrjm+W5Yj+i5R7wNTCyFlz+U8uLK3woQ4rfN46mveQqQI3fxv4LW0PBxXynI5l3yyhp8FBiFB+yXdoUYq3uzAQeYRDyU3tGyVzNWrax1nRLUdS9MSgzxcxyZYXcxIOLArZ+E6LPyo+U6rDG
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
