---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-oidc-secret
  namespace: gitea
spec:
  encryptedData:
    client_secret: AgBKH0dhwFbifzQvILza+fFMVx/KfKnC7KQdHNW/WdAtSvJugBG8PA4MAqxjiV7Hn5mv1nB7JDZMESj6XQjCcf7YsEPXr/nTrLLauNYVp+lVdkJQ0q331si6IFQtqwzIwv/M7AT4W+DH+d1gKe42KdpbkJcL2Av0tMcbs5NMruJ3I8tsSvX1Fu4wQpTcedoHx7M6RRahdrNE0B9zGOALd/FZpjafdn+15ZwvwH1AMomOVj/H+OwWb3PDS1YejVHaYqbmONYkw2odrw8Vl77vVluVM00eOPo1APJnvaXcoafTDtobeyaXiNkeN8ZYOyNBUkIG6tCJkeoIqHkF9ymrILo4NF3VrAB3TuiLs5oinYdENdmMld9Rd3mmGrQTRgLAWFm7uZGmKO9e/9Gjy3jSPbbZbmfHktGZ1zLs+O/OUG2YLBmPFuLXRqlW3aYeul+K+W3Wg/Fifsk1O+luvjYrgy0lLlkzO6Pm0XXDsicAp1Lt8eaBxsjiaB+X5n7wwW5oTSktwxHMt8B0RvPrU0f2c60pFu/kG6m3YH4QI+A+sPSjNRGP9Q5W5/LJb9Az34deryWwuo1wMkG9cB+ze+ZheF7kY6w2mtgp16nlfvnE4y7JS71LHur7PtuPly6wMy8hXGnkvRXLEHvdGh3DETO3RnmD97rxfAQlNXslXmUHyDHjZND32M9CB6QijURV/o7F872KQv9mk3WjrXcxjpurSPrcfbQb9S8BXBB1zX95TSSPpzLdmnJHYhesFtLxezhWu4Vi4AHc4i3nqbBsPnocjX33
  template:
    metadata:
      name: gitea-oidc-secret
      namespace: gitea
