---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-smb-secret
  namespace: chromeiq
spec:
  encryptedData:
    password: AgCJXrULMojJf8Mp4gxrFlFLhAxqcFXGyGdb0SQQ0vVJjLMkU6RRlN64bqpyfmbtlxQDGAZUwPYYUqXvdynTxCjBP1+77n4sknu5VYUb6BHSJwZscFJLdEp7LOK4c74o+DhbCnZPBLzNNd5ovrMcdSHDrA3Mt+8W1cMo4M5wjoQ1ToHgSRZIYyU4ysUBsYLLIdLXf213aTfEG3vnRf+ntiLjYQMakoSatczb7cQZMWnvtwuzXybv8/LI5OsKCet2ghVkJLhNdSekyYh9LvODnOfPOSuJuaFT6VZ8/T2D+6WZnvribwfRIKndQgSgNyKBEG+j7v208lwyRZ+zX01CRuV5GKXpASrMKEht1PoLNT+xbFWU57T1LE+NOFgzaNHWGLoLdNp5a20bCdOU5zFkg1kJVijDEqF+Y9Mh2M/yXsIah5yKFDdn9udeZ91PfSMKpLTYV0BUZtsy/gJ+q3Xy2nLYixiYYmUW4oDiYRRC3N/tLMW351M2OsSDpMtF32zaXV0ixaxDsUblKVmCjCFwvz/Bna0m3F7wp3Wn5viScbbwZ1hoxTi7rLPaQM9T0NjRyCiTbgu/HCbFs7oPdZbl4yor8GjS7xsHBjTqApsqh17LJpPM9UgjLd0ZUpWUU59qWTH3FYtoRwNyvwWdd406AAiqQs5EfpJpqgHErPP/i5lpZQTjuBc4DSSznSPiVZrCG8tK3q+EaMkzWkzX
    username: AgAq9xsCFvo2ZbxglEXPfp9x55dw92K+SeIpPUXgnncBMDNQ4wJbv7OyHmKbPXI1Fu7lSB018Bs05QARk5RWXIfw9sXbvjoN4j61vh7YI+haFdSlHt/P6g4ELlWAl4qDNg/tslq26vocD3aVYKgcmbNPfPnhqq1OAh24KqvKmpOrWSwlUYeyhXmrdB5LvmgutD8oOuzQH0QnGU+V9q9/aUDUL/cLoysu9r8/etuLvVE/eLB7JsBiWN4SchN8yUfa6FHCvR3CAkJrpPdf3/VnlZpdEIHAg8fHGAqYyt6TJ/PcMkVbNhCaD1trOk1TAMKXF4aUwmX5DFc5NwPTUFx8kohrnvJM8wti4XGXVNJoWkIGSIw3MpvjHR1cO+/c0O46JnTAGoqTKvzXtTUUm8PaMygaJO+T55618SfPcJ62cGDMHNoM23uc3OLqMNmJ6Z0ZhtOsBeZjilmkBv3I8MhTsho5MXTZR+TjmWIou63Y0eY93m/QRptD1ToZJOm81Y3KcXr619/ar9gksIHamh2y07pmQ8FLr7mO9hG55JlFKVhYyGERp9zLsbanpoUSjNJA9gGPVMCWPBgtIrxy7Bh1hOob6M45AV7K1E2+sF1tqmUNj8MiPZgBL7ZzclRjMevFvSwkWYADeTfgweUBoyzpmahS7ca58Iscumz6dWyLSBFqSJfOIzO1lmbM1mtY+faKMb7kMTLHfAHLjQ==
  template:
    metadata:
      name: chromeiq-smb-secret
      namespace: chromeiq
