---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-discogs-secret
  namespace: chromeiq
spec:
  encryptedData:
    token: AgCyP2+oJFYToflz0NBum4HLnVvOfO/JCuOsuYtVtLUlszdAT2mcmICZtjNX6kR5C1E3OMM0fOD3CbW3ZE8Rhy1ytWtPt4wXHIrvBcFSqV5uzNptuEB9trBkJQC1equEOOiTsHMRNtMy4TZxdweDtGLFkx/UGUZIL6QvDSttyr9/jvUo5Z8XhYAfryUa9SrwNA0H2NCnO/+F5NqFMBw3KYf8xuOuFwFmAp3AypDNnACPKmADMseqgKylkWI4ZXdgJ34J12LJ25wDhwilZiJfbBid+3EIO9sfsRIrO//1hEAiDRSprUIt01CNQZfIcWCCiPrp4fCReD8TYFA/mNWqCL9f3C00fjzG/yG36TI/BiGqEbKftwYyZ6w0akJjgDIZI4F2W5R1Q6uNNbEkSE9Z2fh2buh7HwB09manzNNDLiyUfEd+ZJEmQFtsKTsX2m78Z9jyeTsWvr7Q/NJTLfJfxj/zhGkpmziblAJ3oZqdzB9tgU3J4p92ARRwOWmCV9LCIGeJkV0Ba+tJS8ZJkp8YG8N4ICszTIzIDhsiMNn2QwTIGmqm4dx2pLtl/KjidsKvRCzhBHm8vWvF6IMKbDUb/apEovlUUTC9a+VMNRHJLT1AjFKnYdMs1W+fF6EKO0x4iu/+GG0UVoEHw/Npn1NUen2WhFfoDr+OPFCb6F2L8Bx1ImG4O8NSfq+Q9G1PqNc68xIjrCCGEXRQd7TARXwTUME8Q0zz7QguFw4Mlu68YpzTskpunQHTYRS9
  template:
    metadata:
      name: chromeiq-discogs-secret
      namespace: chromeiq
