---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-typesense-secret
  namespace: chromeiq
spec:
  encryptedData:
    api-key: AgAI26NpB1IB66EfK08rIza2LOHdb3H0Msd2FP6RZ0TOcsaq98QaypgxSetST2mz74TXYzAcvl1Ah2FkmQNnm7lWmQwFIOtqgE1ebXTQprPQgXMED8BBi9II+P7GkTA7WBdoPisqtZn9ofiogshTaoj71i8vNn0PadoKfeHIE1tQSvRO6bLLCleenMvmO1YO7QARqGlCRt9QMbCNytBfJC9iB9rdsy/SHkCTdpOR2/tW1J1g/CfxXbIBN7XakNPlznCrCSIWjJ5W/X9tuaq42plFAoAM8TPA1KjesHoHzakPAXXT4nRDzqf3Kc7/hQ2AzDVp4eXMn+l72tj5m+CAJJS0NuZir6bV9lO7vDR3ldfA3VVSB4F7FGjEERAKkIWkaUhZoE35VvCJdYhUzn3QwyxYFgqVZjJa8/z9cG73qGvbTW5yGuDkylla3O7fSQFVYkBzYfeFj01AB6c8AGzmB6B3na+RUOGW+PCXAk2hXZ8XJRETzNmVYc8nymj3igx9xE3HcC3Kag8oUcJSKJpFosRoF6hHiqZO+q0mbLDlqsQ8zlvIUETjU+LfqO2rFG4tkOCI5mJUBvvpUZaihoJY7f5HokKKbcrzXSbwJpszKFtTX0ZK/POaiamoOj68iFp3c2jD0evX2pjg9L37PKdrDLf0zSROtLsjbYK3JL1mm9OUDrXVy5Lax6ZzGL29jLI0j0aZJUHpQ792FDG2Nh73ObkGnWf0Nh8Q668FPXBNrociQs3vjsIWxvVc98S+Lzfvhjoc+BFauqlEOaAEonlKxswh
  template:
    metadata:
      name: chromeiq-typesense-secret
      namespace: chromeiq
