---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-jwt-secret
  namespace: chromeiq
spec:
  encryptedData:
    secret: AgAz3M2riS8+sDnBXHBdhqBRceDcClwYsYiTZg5NWJmZxyLax1koPr9dc2HpisEDgD7RZ3X4jlOJc52boZ2F8OKhOMnb22QbopOObJNuq+yJBAnTMzk2AVIGazBTVt86pQlHPw6te570tF7whXNxORHz9i+DNTpdG+Hwss/kwyxSlH6xh/suvHGUx8jlExr+tX9RIgYZqpqNR+7AfJsGoOgRSVpJOPZ7roNaS9aQluuaS4/oV9pROsOgFxSP1sDMDNKPlj3zAV7NrpFD9alPSyNT5H2xJ7eiO70LM8exyqmzW/olKDyRgM0hrgbTR8mIwctTWQDP8CgqeE7HHSonS9Y4bNYCdDjj2/BwTXi9qByQBZ5XnBB7idWCfZQ4+aaEJ51F96ftE25xCIN+uXwwkkdSNHzvEMBfFl1Pdeu8dvQi64eO0xHoqSIOmOBZasdeNIgPt/01S7tjEhNCcL+5w4wHqvzHVWS9OPdyWru5hWL/L+vy4wdzkfF/7b55GHcfABR3VGDbl1KmUucpfEmHOu1CxNGlCRJB0abXGmQSjhJSJy+zdV2R64iNOiq7o+2eFJwD/WrPZxjflxnH/sxJP/klpDjLBdzghl9A/vrm4XtqtA181kfxmfV9iz5UOaVlbak0UUFL7f6uQFHsyB0VQJjPJduLpLKyx5XphPUwA3eD7vAFxGXwS2CmIVPze6ZQ0uv7SPM0DbTsl0CmI89nJ3AW5WDvoweR1O3wp3C+f0pwn4r8rp0WiJhYiDhqaiCdsrXr/V46W9629Li0hltYc7ga
  template:
    metadata:
      name: chromeiq-jwt-secret
      namespace: chromeiq
