---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-postgresql-secret
  namespace: chromeiq
spec:
  encryptedData:
    password: AgADsP1K3y3dGRDOhaPO3vOwnVBImHmCeSabipViw28wDLCL6vCGj8Z/ppldbfgioNjCGoVjd3O4NoRxCWD9pXvKho6WbNnNTOlDhuOFZRertd2cgJ04ENNvtGmVVAAJ/rH4JXIrThtSexlIa0UJ2KuhqQrQqJONrgSZq4Z/poLqzOpKzIi2Cd8nhySWF6hk4kIid/VXwPRACvGhLsQ2Smy0J2p0QDoAVREVuxiybZ9ZXRMG6s5lnqU9LcU39b5WEU8ZcfTPg85Sbo96HeY+FrXdtqOUjlq8UWoLUTFo8kEIQOWqR55lrxAHfk8I/jpX/vIndyCnCy06l4zi4m28iouOA1lWrIJ0jeWJItXHKSKDQe1xDZ6xxDcSv/LDjuZDfuzQi2xlLSYGv7n2+oSJMuT+mTXyQnYwNybfPPoGj4DlhI7ZedGSzlK85eeiH/XG12VTkh3Z6nPJJRnkah15qrn57irGfBMFTD9WINLei4Qo2IWVAESWab+H01wqBS0aEZ8urupN6y3WPUWRyXqJIPRkk43h0V/j3l4lul6NdY5ZWrJ6eaV8QXzbCG27juIVWsd94MrRxuKdzjW1y6+mHAzl+oreH8FaJYXPYGQMVhoc47qq7rwvrxFmzSAhqt8pPMbEssJVWZqCw4DeGG9Ptjm+S2/lN+PB6/8MGxHtgSiAlJTeOZ4dfAiFKd5O9A6S6e0Xs03Kix8mdXV9SQR4GlC1DbtfDaV8QCq8w/Y/ndUeHA==
    postgres-password: AgBfS9RuWYDP51JcOIT6pEft5c+8jPawvmVcNrMRSMRsroQiFAICwcMAcz5/ti+winN7Wr6O3jIR01cImOS92viRBM9oV2VNMNetay2grWb6voF3lkBhi8hILX6z1TAttkIV49hvtbP2Lw5kAsyYOOMkuMMH/7dI6Q+yY4edPhGkioJ9QeEIBFtB6QRL8yso3WeG3+S8T2QIngnpcfl9k7+NHSojb17+ZbSIWHkaeqrGG0mb22TU5UemrXAzK3hSAeq+lXQ1YqxfxkXYx8wRTPmc11Qa/9r3LDo0aCFvmzYpWl8RB5nklpoVc5yPRwItyWm087evBKTJnLVRi41ZuIbw9xPwQVyR1jihkhuYYQseu2Amcv9TOJKQ2QLSeXNfcxP7ocbrH0lEf9mwgJ6IdJihh9jBLsFg4mZE3KEhr472ucsC6bMbE2tSNwGemKWkHWstc8aDkNepr3MihMlAcPKGmgaKruUH0UMnc52AMJel+OhDa/UTelE7fNuMSDjqNnuh7RklHw1ZdZPVi9XNO9CxHmq0hDrdjvwcWaJLUJM7/7IBonPVuGbvDJY+TAkSSiJJgq4hhlo3nazM2ivBjrKAaW5JL1V77OKjkEi+OYNfBEwEbSKQBeS4WGoZg1HeooqOL2C9iTbNcVa3zNULErwzGIt4Qwof6+kLdGJBGZtkuPpk2j0XXDgAlw/9oXiY1kjBB16RK3miW34fIXNXcMBO74c3seJKx6L2EJPagp0qcA==
  template:
    metadata:
      name: chromeiq-postgresql-secret
      namespace: chromeiq
