---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-typesense-secret
  namespace: chromeiq
spec:
  encryptedData:
    api-key: AgCAl82bNjv0b8aSbuJUUEsZK6/GnWQjxRhEVouywXPwQmugc0L9FWT6slM2H4vGJy2Xztyg760RZsrbq2LcU7K7MeliIaxqYPI/2tAN4H9/QARoKdF3eJls/NPJhIyqlg++FH4vM+q+Pp85GBQBdKZw9Ac1loRBibsYzEFFRCsvz3lPVi7Fh1Lvopdo2rxjWk3mXQVPVsy0bTlQn6W9y9os9y3IYk57VfRbBpdWvuluTXvDhNMG8aGBnd+icMOZmvnqJf/JnkN/gDmpU4VR+IT+hRq9szeVFuCnP8u8xbWFp5DaPi4u2nsCz1tzMGoiOfm4Jb54QwZ22O05DApQcdxTFY26GZWr9DQXzTbJzdLf+CJAw1RztHMvQtMjYTYUPoH8a0PtgNMHU7XzzCXCXqsy9HekUqD1KBPWNDhY5JVzC+Yu8HRojeBObOubEzBIqUGbLJ4xfpWLTNKwwW7O0twbUMjY4QUmhPnDB34e+M964Dms8q03sQz2JNMF0YEN8iJ+wQH1pBAG9KUfDNtIjWR9w0IiVc9Vi36p1cPJyL6FNigo3cH9bicyt+L78L2VfpVJjifllODYtngeYodEXWaLt136DukEshdiU2jpt4oEdhLVNEIYE9Pe4hfhyyh8gFA08Fc+GlvtH5HanwhnG1xob/HlzGsMW8lPpgPOanTsn0ic86UlvN8SosxgYY/+fhsNs1nJLrJvOYQnQXqG7DjmFdXHBqIUNhs/SUf20zcJq5RxnqKmY1oOQOPI1lQfh6bWEFLuKBDjec0QLPfZROeh
  template:
    metadata:
      name: chromeiq-typesense-secret
      namespace: chromeiq
    type: Opaque
