---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-postgresql-secret
  namespace: chromeiq
spec:
  encryptedData:
    password: AgBcWDPnIUKmF1zXtTjEy4URrnVUqk0ezqnWxgx7VPy2Agao+y64KAeT3WsqSAs6Xr7J1InD7N/0yfAvMbpIOHyhvoO/kX3R/ICebXqXAWdSG0fUj48qOgw2SGGh8TyvdwioeePAD7kOX75SQ2K0aD388LA9jDMwTLSHJ15ZXg6jzyoNMA+88BGA25dCc71y6e2LqpHqxzL4yaNS2QKx95yBfCZY3FA0goxq0MpVZfnC1fdB96/NvhoScdFVEvmU/u7Z3FI6b/IgYq7322i4txozuGQoAFt6hsPhnYyHq+Gtu2nVHEthmgw7p3aq/FKikXBCC+qRLauCTj7rckyVjRZc5wRyTFszz9z629a25ifmY8ddGTuKk58eA1bvjE3Z4GpAUhsmK3pQCLCFMGCGS7hXih9hPv1CjcnvsoaWxFE1+XJ1p5fFpPjFpfgryzn/au9+6N75TX+zAPfcpPQV4r5oNrfzN4Y2g+qbif8vpHENr5GuqW0atmsDkEBW5+f0rIRmy7D/U17dlkV/uDps+V/krQZR/YL+H07DntnayZwViU/L/8ibv0dXrNTEU7xNjgOnfgTFqfRQxxViP8ZdCMEyH2PvBmUEWYCxZoFo+u7k1mz8Iz+XMEaAn9LPNNxFgrp1q8vMRDBwEJKSXqZV+1N/CCzmkIg3uCWvxfRj48o+WYFVNH6XdOXm9FvA2PGwXND2zNaeYjYWPpXl9JtlnNkdYLY0UlGcnx6fbe4blyDecQ==
    postgres-password: AgBlXZC9cdpmznI2fy26x6ZJUlRJ94dokB6jwLzZfk8ImqyT2wJAXtPD9wHwtNpYtlSDOMADqveCGD9LYw3uUdNoZL3KYFxLDBTShIouQiT1+bFIDKaaQ7MddEhDrwNArDLda/wN+iMKaQR1FWqCPcpLdzmPCa6UMEADHZD5rAFLlbL8jPdYB6/gHLMGVYGz5he8/1ffxacjzqtb91tY3OaIsceIREARpcAKiY0MCy4wj21s/h7iu0p74vb/7bO0NNTOt4+oEJztV09mwWwJeXpatojGJtd/UPylCaeZtTJzhl8a+GFrVI4IGXs1zOC+i+wJES6lAUh+Wu8e9Oek79KmS2SgBuv8Bo8exGC9yiGg9/IQBfaFCkzOHn4Zd7eIQLFhZ/ohYMkfs0WYANoPssQmvEB5Yq1pvieZRvDJ7/lgNYxwhDkYJKMkE0P3M5sw/wVZr88MuMxtiSURJgDuRlBi9s8dcjPjrTXXllOulOgFab/3scDfCOULpQ+3XfqBJ06O+IHsX66ek/57Moe11eKMumDIRrMSoWwi1AbPcOTE07bQ4vKs0xf/GCm8oSVJerMPiauUITLZ18YmkRJY5MgyOShjc0r4gF2UlKjyeOXQLAYlla0je5oUfMTAMs2LddS3q1voaIeyRPR6J+u/oX/MtYm51T+5Q/EW0/0Be6V9bjT6UaK3nCkw/B3D1BAZQMGimN9e4CZfg9sylkXMyjRzn9MRzRu6XOP37mm+yh9sDQ==
  template:
    metadata:
      name: chromeiq-postgresql-secret
      namespace: chromeiq
    type: Opaque
