---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-lastfm-secret
  namespace: chromeiq
spec:
  encryptedData:
    api-key: AgAUwVLfqOwhJQF18f86HTovu5L5gjUgFpD6zWd0S3w6kq6KG29cTz2Gh86K3ObFZ/FIaWbwg1I68RAE8w3ZGU2aPt6CvTu3UiYbp0kGLxWjCrAx82LR2vpGx6523j2DipIOxsimtI8r/NoXIwvGtpDtrWOAe//gl6lQf7+L7cHJYimZdJ6RNlqtw1cM/ekde3D6+k33EGMzhpZ6kLJjePs8A/Im9vEHLgsR6K1LYD0McCn0V8cM6z3ESImYnMVod1VfpsUX5RTbVbiu2t0nPZaY7nz9VTt5Q3di+E8GGmKNfaCzjn/MhKi9MeFPKKIHLwNOa81S1iWJPL1mrb8bUnDVKcTdPAENkHUW9vwdjA0m0q07yAR5nbtafsMcCANrpK7uQVC38qMeR7hzcLUMHlybRXKF4O814AuSJlF904TUnhGmg7SYqLzZvE368a8+GONIYeZhAoiJVGyvsUUuI3OCc35nTnMf25wz7LI30EE3kEFKftlqecgpPIsCeUwArEpkEs0Tbbntjx6ebxR61F1z4UBJKTwLvTj49S0lZZ/dpNq6YR2KPk+BYfwgMHRp517NQ4g2AhS0Zpgm4GDkyqknDQtMBxKNjX+zurA1fpofiCBpY2CtkhMhd9VZ9MBOU827bSl8WhsrwXQ89/956EjJ5DIXKAAzGnJB9P0Dsb5o+UeofjMZyX1q+e43ROTei1ZoyMOTb6PhQdKoZaRREqHDZ5XS0OwzW+wdApuXdtxiKA==
  template:
    metadata:
      name: chromeiq-lastfm-secret
      namespace: chromeiq
