---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-typesense-secret
  namespace: chromeiq
spec:
  encryptedData:
    api-key: AgBcXMelJ++z2waYTQUcGshZEExhydRXgg0C+eC8I0RIJx7/8ySSRl91T6MGYX73Gmmd6bu3pP21igjeKnIEDZddEQmw7G3K6S5Slx9NfLZxzROG7v0XS8lBzW9EH8rdFxr5z9rYgtg0S0YZvsqMPWEzUvZos9WhtQ8lsXeTLvFtKc1yb+J1GMZYzsDjuGvyBVt6GiZ1SwA1j30bVYOW7P8DurMBKSwFRGyAW8uWhXStgyNPVnJ8oCd8U+ZkYE3gmgJDh9oByhcx2MCH3FC6JgiWBxhsS92rxn3EZYQnKrieq+iG6yR5ts9DhoJmIMG+2ezlsOKjhq+56G7A87CJbKwuLq3JGLo+QD9NlpxpdCckl0kEr6nd7k019FxPV/nplGy2jnmJ9o562nL1j+Ax8V+VRJTKjY9TK6jISB8XF1M4ZAS6TSF68UC0XlOgCIlnflm2mvxlcukbm8EID+iAOOM4pMevFj7eouc8u8RtfDLvTcdWJe6I4eUMx1HIlnFVgkSUo3PzbUfqYA2usTHVWIsNROHq1Q3phuRdEVXqyahkHmwXxSa++Nh0Oh/41nYEbtcHvYoknBEW5LnEdCiOem4yRiwkT+gMQLBoXHLVL0NrOOqCADd5rskTqfOlPGL1gBdxZsaJJcY0NXbWyc5KcPrtl5a/EFOtfu3TqyfVzhscwam8vjT8hBvj1ppzNaL8iWtkUmyg7uIa0T+/7YGKIg/ckPlAVxCr5FRi83UJKUGJaYbAVTSLFpUlEl7xEPzgPUbT9+f66L2u1/v6+bOGN3bY
  template:
    metadata:
      name: chromeiq-typesense-secret
      namespace: chromeiq
    type: Opaque
