---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-postgresql-secret
  namespace: chromeiq
spec:
  encryptedData:
    password: AgAUYXaLYf1pGSFzpxC0yLt5CuejL9XCzh0Xs5QVwCMtF+KfxFalYa364PAG3jA36dBz90ghy8qA7XJFaX/QRqYBWezTngnq93on4g5atae41HUQJgzPvbBtgs8TXazY8UPCKdLsjliuQmDfM6RYi8pxg9TL9ydgrvNQt83Vu25ezyIn8+/74b9sADgYVEEQYJtzXzHZ+2UqPfY0H8CfZlT9BjKd4X1WRJ1knojgROwNJeyyndUQ/yMqPcjaBbIjolMPI7FZ3j+qMscVVCDx4DawY/sRk/fCGDEm6RfJ4VIlrOBMZak3DNcLu96hfIbQCvee/h8YTejG6sXdTcULBUZv0IknOJzHSNLYCSghDy0E6lyswanOF7g67PNdbAr3fPLtMLquXSuI4QJDrgxm6Ze08C8BkG512nKi0tHhXsbjpXa80wH9yYCRyumLH2t/F6b8q+pWZyFrOhMZPqYpNlM4KCkVwOHDbh3gS2WgoBda6FARQZ9qvCIxk9CjbEIMceajGm+eeUYWJyyVZ2qqoKputkCVb0wdKBhVjbgjFWgw0UYFfwgzIZTTMxd71+o/rMASzibyOyFOxvBjrn2fEqMWtGjmiXxi+gTL0OxiYM1EVhluJ4jGEYhLDi2t+v8PU5NokH/V45RoAsXPJuOY2fmfQzOqqbwhqMW7rAq8JRPkhE/FwnzipO3w7PtL1wCAIUs7yJ8Kg30x4op5HcseQPA1THd50uD0KH3DkHGcuLeFgw==
    postgres-password: AgBdWGKE4Qe9+++ESvnZgRl7OaoHgL+UhcweSogfuUhUAGrCrrctkEYme2UQvhYSwiC5rB89qJ4CuRairZ0siIaSHlr5udeBo6XNatSiihSDgXSQf2bmFB0wWkP1PxKCh+LUbqykqJ3w59tzGgoQWGSUjQ8fNMku4Axhbdf6EBIZkCrzjgrWjYpvwNrPp9BzM2lae+WAADw9IWHqn3HdhmCbImryIyyYoTlay82ha0imTW6W332IGvccbAbwbX0YyqjlgMkgUApVWsnc0P/pRSYrFcGY2+1EDdnAcUwvliYhl4xuOpq59xKTbD/OcXHVaXmp6bJvO5WvKMQFpP4BHPaVZ/jw/xMhIhEWnoEn6kPe9ypP5HF/BSDHvbKle2MyNtSWIcdyBWC3w4Ee3JD5ZzgboLlB5YI/VVLqHpGZA50Ad9l3SN0FOcsQady6Z4TJbDNWEC2KJ4dReOEFbNWnWcYbewHzJFGsUnXLfgQOcFMAMLty9H+5rs31PiLxbvKs+2DKgNocMjkfmwLuLPVuVw+cmw09VUXB4HbWTvIoT5SHjUaH6aThkEzp/dhPruQhWSSYdsFq3u7c9kglTYfK3Bja5dQDLsQ2Hrajlu+iE3BujkJ0w9gwifaw74y1moADv/5LKiLWp/Eo72aj3dx6cKWs887NOu2J+Z0gEvt+FF5mO8NcQ4tgKwqNfPSVeah7JdNJcFsFQsGnmSWNbdOeNfXeo9hWlhLgKOVK6GrDqdD5RA==
  template:
    metadata:
      name: chromeiq-postgresql-secret
      namespace: chromeiq
    type: Opaque
