---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromeiq-discogs-secret
  namespace: chromeiq
spec:
  encryptedData:
    token: AgBtEvl8CY1kJ6w8E+82cF4VUERhzBDXjXpRXr/7hYE08pswvpmi5WqUYK70qSKTWhu9jt60FIYJAOyKUgY4R168iQaNwzYJeoSmPO93dHp4h7WcMRfOHNczxqF1fJLm7QWbf08+REzxv+2CPzKZxhEnhfUFqtFaXgX5HfSLPqpgzYoQaoAiHe/2Ilve5af8ErJqBoDzUPnkTD9M2Itygvbn6EsXk3YoNnCvXKd30QzAYT/K6Yxce0h8BcV3DulkGfl9i+fLR1xCQcPghtOy+ItGq/+Ss0Zawae+QsKl+AS3TSPu2PClPhmuqJlA86ajwxnv7vSu8P4z2Wd8WRI6dcL/1nL3yGXBLa/VyZCPfbPZewkO+KAXaK7M2QwyF4HsV5GOxWvOFIId7beGPEjM+VfTbW75q6tOccHxKSqj/mLqLjwwVvAnGu3HeWy+E9yQjnb7gdIyru7ErRSLDwj2+dodkCYDMgkMRPIoxpownVgTa9Qk59gQZip5vmGVG9zObq2RW3tjgUY21SuCSz7lASM/G6GwwXnhkZA9yl7Nh5sL4hDiqUIZSVYbUp6TwKRRJBPjyjIGR29/TKGnMk6oKvifm4dH8xpCE8xatfJrGWjJjL8LU9Evxjhm2yD4D2KbNjUSsEXdiNMz5TWgZwB4R0q0FysyJ1kqgF7Z6s6lL+Fu4GrgRaso7omCOi0trJONHaoumdjU3AaaJy/OBSCNiO2ZgSGNd/xUrVW23gNVp19mKPm1KLocEsd9
  template:
    metadata:
      name: chromeiq-discogs-secret
      namespace: chromeiq
