apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auditique-tls
  namespace: auditique
spec:
  secretName: auditique-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auditique.reckeweg.io
