apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: "1.5.3"
    helm:
      skipCrds: false
      releaseName: longhorn
      values: |
        # Longhorn Settings
        defaultSettings:
          backupTarget: "nfs://192.168.11.55:/volume1/longhorn-backup"
          defaultDataPath: "/mnt/longhorn"
          defaultReplicaCount: 3
          guaranteedInstanceManagerCpu: 12
          
        # Persistence
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
          reclaimPolicy: Delete
          
        # Ingress
        ingress:
          enabled: true
          host: "longhorn.reckeweg.io"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          tls: true
          tlsSecret: "longhorn-tls"
        
        # Service Account - wird als erstes erstellt
        serviceAccount:
          name: longhorn-service-account
          annotations:
            argocd.argoproj.io/sync-wave: "-1"
        
        # Pre-upgrade hooks deaktivieren
        preUpgradeChecker:
          jobEnabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  ignoreDifferences:
    # CRD Webhooks
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status
    
    # Mutating Webhooks
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
    
    # Validating Webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
    
    # DaemonSets (Longhorn updates these)
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/metadata/annotations/scheduler.alpha.kubernetes.io~1critical-pod
    
    # Deployments
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

