---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-secret
  namespace: headlamp
spec:
  encryptedData:
    client_secret: AgBtjRLNpJz1jUl1kVaM0O43aomm1osrZPBHBLZ1FBbZ3jrSwRWmd2nV/qI9CN+dapxs9GlZMP+/RxGx79GZxGIijBjmijV5iMsfPpWI1kgzvw7LiAdfkg9CcjHmLqEpKpKut8x0xWioS3sQfBxR2txeWSJIKGN52pQ8vdtFaD86OTUQuV9x6/ZZLZZbsVlwtbwKjYwP00kIC6CYXfbZ259SmKwsIzv2zsWQGySbV6fE9WrJ2dF4GeMT6rkAsWVLc9H2OtX+17DdJgpDo/iiVBqpRoY/OGYf4yM4LRFSkmkA4Xv8tOVOegr5c8nM0aqS1opaypUHsM1xymXYKRA5EQKAuCjT24zSEPa33FXzlA2wskk7boYZ82O+J3HKKrrqW10vzlluw0PMZ4VVJYymjaL/maqrqECSLp3qY4ziuZ7mdfNRHQV48zXzNK44hABNmDf2PjabIh+A9ffRy7/dO2oT8KL7Dua/kkcacKXbmgNOlchKnN/mm+7UM3voTTW9NInWDKIdwOgqyVcRU+WHnXEMV7KlnyqAwFn01aRxYuxdQH3LEDBrvDuBIdz7je3SPqIL3eXOS7170HlSN023GsOLWJvf/7wQ7+aL1kicIiwIm9m4yf/XNxYZwbPAqvHDwILQI2DJkJYvrelQ4rBA5rQa8n2Xc3VPrvewwsqk+X8ySSKdWjpL3in00f4GD8ubfknHhoqIt+LZe1LHcZv5hlQd1x4Cp3EFLskbvtjuMvTy4BJtqzmauhzzcRce7HlTOdZEPdFiDwSiN8B/f3pUaW6o
  template:
    metadata:
      name: headlamp-oidc-secret
      namespace: headlamp
