---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-oidc-secret
  namespace: headlamp
spec:
  encryptedData:
    client_secret: AgBSKkTlcHpr/JrK2w/vNTl47DAPb81ESUQRV38kI6ouyyxNzSAwjrobotxxUGFxojLMELClS1ARLed2J3BsBnU6DU7isicNeHcX0a9os5ngANLsTImlg6Tb3QKzYq7jtIvCQjWbf/4JIRnEqyCGaJYSfO6UsA2NFbrjNoNnjIV1PuLOyZI0akFh90P9BZsolaVN2ZdJGQYS31jQK5xu1yWG5xfhKpXS6Wc0weIMLQSyWs8iAYecVwTI0wV0pV1oy9GuI+sJ+eHba0DnNtyhiCAyc20ikVzVcl7kLt5TDrQV/in5IYVUfHcyExysK+rKTaZKaqSi4LZZhSr51jwXE/fnDJL60sNCDfAkvB2JgSqUywa4yUV0ucRPBCPaKdN+Q3xPPn2WGCRe8mznarRIsK6kL5BoRmP0N2PLQXGgIfEIIxKudg4rHqp4RBzPEVQ4sIUXSvVG3/Qz7F6qWRMXqhVzUwLGprWzGPCHzPBbcNJniJX9NgYuHqMgR6/FO8yqYyDc7MBBqANZ5iTQX1grq+RSPdZtV7iRqSfrB0agNB+T8Lv77SCSFBDiBXh0wWtmJvB0oZjqrBBKPp5aMJDOwL6gd2hX8wP0RkCCIbYg19KSBnvSMKvn5OYB3aS4Lh413arYMihtEA3D/CNBWxhCNYN/P+LsUno2O9Ti4RgUtbK2y7f3nbM09C3XRp04uA+2y+8p4OtMCSuacONAWLefeD2Yi9W3tr+r5CglounZ9SgadrLGUu4yvlcwcg9jpa042VbYy+EeLml+OtG57xhrkZzc
  template:
    metadata:
      name: headlamp-oidc-secret
      namespace: headlamp
