---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCUs9J6CF0f7Ps86G6m891W8PUpTJtCccU9HcHui8hiGsmQbkdRo+2JgUjMD2Ith4ECiGpBjVOnV3ej3ObXNJnMv86PFC01+UZZ+nN82RJp1+VbrKPjADQo5/Txs8f8wOSCcf+CryQ6QEZYRIB6oyRYJGIv5tXz/bak1pcgHx0Fpam/9O/oT7r8TWtzQQY0T4adnCDR6VQ4MDJD6H5V+c3Jg5yK2wUHUDOQn1fBOKxOYBBQ28DVVKs4yqpZI4T0lnAoHNTrI1PIXSET1JQF9a9jL5M5z2+R9ZH+7jr5jsQLEunJZJm3Z78EcwCUxZfJZHTcHuEKeOXIik1uj0dfKxjT7iDMjRht+Yz0Frq/rPNdlS/baHzrROmg+WOLTOhasWGnOejZdW1u84qUgVs9Y/ARLWPV80FCj8bgiYqXnqexmozkC+plTKQ2OtCAqPa2OpGDPpjegWXA2Axm+s0C1g/BupHhpxjnNzroavUl3hBrqpq2FrtmIo2sZu2PcQyw7zfOQGx3K8dtCQD0O+fUEcgjJjMxQigiCmVB2/AJtQMvW57/4XDziaePSr87/bxEXJXsLAVFj5HaO3cKpfOEMLME6eBQ88AacEUnARhcw6XW9HstNn0Y8l87YZHzKB99rZZsspa4+FcjgFWpnnYQmrMViqHUPgQ2xbwwMpJV1VHg1xyPHyGuVI8AZYLJcHU/8+5TYreA4cFYX1XfdQ0CXVR3zphZXSfX0RUN1Ww80hQe6nJ7Iwo127nBm0rEaW4xUUDHxA3/YS35xRSvve/Fl3ZKoVZ43webD3lGzqAUPbx3KVk2ssVN9eENwbzDP2rSCr+0Ep748Zz/a0Oaf93cpD8srqFTp+jJQkRzDiZ9xNefRmbtc/FdlwCjC1PLvawM6skcZnwF/LT3YND7F7iJjjPoNT86eEzggMrOgKCiDXZG4/By5xW2
  template:
    metadata:
      name: gitea-registry-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
