---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgARhDdugMsvCANhEK1zt1ThhvCIutQ0J0QlyVFYE99wc3NjqLOixWDqMQWMoXncGblEPtLhYBfN+NNDaLo9UsX5qj1SaB7xVBolsUF5mr2dnsVSdoxqlByOmyLN6HEa6Ic0xbJuJ3OhnO6z5FrjAS545YpcbyWMcohOPmR+DNNYBgvS9n9OmCSB5SZbuyon5ckYZqGXfrRUSX0wl/aUZircP9g8wWon8hgxJ8x0330t6Q5x3ZA/yw9mMDd4RVaQnzODAQ9KRYqLHACXVuUz79mB9xq4F9AtYEPmhyRdBMJ+llEl+WheH7Bz8E5H64aUFxunycGGyZrMDbxvTpGaEKEYYpfYFnTLP4WJ/ngoMNgMx+/0Rvn2jQbJ3XMCR8w0SMa+/VIvgaDGgYSkIaZdMwhPmGuTQJifGHy7wSwV3sKHDJdoulDz0cgG36Lc6hO4cEc7PzmZg/lRr67gfG/lMAVa3IaGBHptQFyKB8zNygppwzua25/QKDrk5voJ02YzClaCEj/toqj8W2pghGKrwcn335DcZncuabduRGn8pnTPreAy1qQBKxJGcuq003e50tUluh/X9wIrlgDKVv2Msr0n8bUdjV8oGQaq+7gOkXk9VOi5RWMjvx228fzGW+iC4hj4xwRTX9twijxzzor6/Xj8q67YpKiEQq0d2XYTXyZyM2P57w7WSzvH+0obeysPwEmsu947Sq9yHbLEYji14cTMI8R1ZRHUzqxOd8Anju4yJp4FvgZ69WD2n21AY8yv9bA6GDMz/draxphwCrTcmRhKduqAFqQpK8cXy8ltqEqxn+qFnpO9P+XV6O+dSkZBlihhJDYOaorJnI67376OhAVlkfp4Ymgs2pdnGoAJOnLnz5JnElErQBipnqeshJ+wpHkjNfuZKboUojNBNbxIrwLgmiWj1GNkxj/1c2iJt8jwhsSqN4F8
  template:
    metadata:
      name: gitea-registry-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
