apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  labels:
    app: headlamp
    environment: homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: "0.40.1"   # aktuell Feb 2025 – ggf. anpassen
    helm:
      valuesObject:
        replicaCount: 1

        image:
          pullPolicy: IfNotPresent

        # Headlamp im In-Cluster-Modus
        config:
          pluginsDir: /headlamp/plugins

        serviceAccount:
          create: true
          name: headlamp

        # ClusterAdmin-Binding wird separat via base/rbac.yaml angelegt
        clusterRoleBinding:
          create: false

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: headlamp.homelab.reckeweg.io
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: headlamp-tls
              hosts:
                - headlamp.homelab.reckeweg.io

  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
