apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # MetalLB Helm Chart
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.8
      helm:
        releaseName: metallb
    
    # MetalLB Config aus Git
    - repoURL: https://github.com/arx666x/homelab-infrastructure.git
      targetRevision: main
      path: gitops/config/metallb
  
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 2m
  
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status
