apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "55.5.0"
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: false
      values: |
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 50Gi
          
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.reckeweg.io
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.reckeweg.io
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
        
        grafana:
          enabled: true
          adminPassword: changeme
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 10Gi
          
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.reckeweg.io
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.reckeweg.io
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure

          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-stack.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
              jsonData:
                maxLines: 1000
        
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 10Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        maxDuration: 10m
  
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
