---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-oidc-secret
  namespace: gitea
spec:
  encryptedData:
    client_secret: AgATRG0dL2mhoL9u/lbdgU3CkRcS1o3CaHvo5D5zvmf1OF/Uq7Yhq0H2m2uWgQPMwebPF+eCm9kXkNF+QxpSlKFK3P2rbiVCqNVx1HVE1J53Ww1OUWA0UHgk+X0SOuO/S5g35LWaDRdY/CSfonUjJrio8fi6exaW4G7t0w+b7BEIFCB92p0/W41/+HJicje9NoQfQKFsFyOJ/ZD1lYy8wOqS4Xwk8ZSV2i3QOdIcQucmiGHEAiA/9W+LPrCLZj4MI4gqCZHctgc45s9f4jGQtyyyeM0kwiZ0caik+sDxtw0KqZKg5V0gMA7aaWviq0vZfkl5Ov6j9VCamCD9q7tEpXqFZ25GWAT0LKlLYgW+JcI5sgPfcfZWlP48bIp0FOVaZiO0WxQnBaC6FvIij1F+Irq7Pu/ICeDORhwlXzgQXbKHYyQYLDJiwm6ZsP9g2eSsHyyO85BlSrS7M0xUV4KQY2qBRX39mM1g2WG7tCEcJbqIRWTHnaVUytq6Az7xSXNZLU0Gs3SPb7VaZzCOk/WHBUdFD5Dg9wb6vH3dJeg/szFvvFfy47IASQ7luh+QKt4cUrl9/zwsqWio0XY/5Q7+0ZuoWUf+jjlMMSxZFcMGuOgM6sDpWeaByZN3hfQxrPvJQfmcsGbfFhfDyfOIAAeQJt0W8XJvWYbt3CSdqfejulyiRMUmVXritdlVnq4T2dZ1nJbrQC2Bb/2zU3UyAQJzA2vj5+I5ynuCuPf19ztWh+4hWf66h0ip3qsRoPhvb0hAbHhqo8B4YG5T4e47JN9tgF/q
  template:
    metadata:
      name: gitea-oidc-secret
      namespace: gitea
