---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-secrets
  namespace: homeassistant
spec:
  encryptedData:
    MY_SECRET: AgA1knIDtKlI2BLiBZ+sDAFMbSJYR7iV8QRfZiIhq1LZIXblDFWwFvG2R1+VtQxadDt5oZNJm/GN2s9upYbSF6MQazwdpxcp3pVQ0NOI09QduWIr9IttZuMvdSZBekSHSqjBlavGEMvy3GiCgrcvLi4H3g5EuvlBWuZNk8cdKG5ibiUHFN7jECGTu8WE3f34N9GGuGDMK3LwrwD5JDymGM4C9fMi3JK3khw8LweFy+w3ZJgq8Q/wdbrZ7pQN6zxtbemvAXAiqQira4AieTTYOlGuh/t15VPtG4Su9gAvTipQII0/f2U8WcvBw+4+e0rVXD6/pcAvCmVsBoiclBxwC2CxtYRri775hPNm9mKFaCGJei9PoyiQOpkd9iUgSATp88itSQryQ6TXm9XbG15Bh4v+c+5hVMUAPLsnvktw/djDgnz4Dg5vMnV07gUzNpYFt27jtaTSJ9VGGWzZ4y85QElt1uz1kadfV8HbmGF4hoPUMXR4JEmEuk1Rt0ALSJL/dd3DZ1ONuM+zV4Jwkowbhz9flbfMCen2J5aZgHHEZ5xWcqiKpuZixqyIh9hdWaf0mrf/C6xp3gryu4Z93/iqOiqSZ5+DaB2UNi3pPcjWVCIXlQcl4m6gffn/QuxoAqIiGTl/4TS5MxoSXk2J+dFjxe7Qlfs4KThF8pYECYD/gZmcsO4/Pauh7KJdZGfjVoh3cxQnj6RoAd5pTLTcK0yX2LyDpfA=
  template:
    metadata:
      name: homeassistant-secrets
      namespace: homeassistant
