---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-ccu
  namespace: homeassistant
spec:
  encryptedData:
    password: AgAbLvxQt2wtlBzYX5Q+ClBC6je6GUuqRqPVUSXuwqjRGTLqVT87DPn7/dDWN5melLP7iGlTf7L64EAl9dArEaYCGD8XL16CCNaMlzPbc67L3VRiLdTOFDeb8Kz3NNB9lGo84ArNMqtUq5jYbhg/o7OBsV1Tz5TCU6G2Z6x3COKEQNiQSUP5gdtZb8aD9GelkJUzZ/GcSq4A3b9O8x3SWgOuUvuthSEDRzzmYG6LRWMIj8RhcJyNbxufqE8og0b/KrQLYfIpRyvHeBdQqK5BdU3GyyOQIddQaLg0gEIbqI6BOTseC5iUCey5HHTTas7pmvGlnHLlSxmOkVC1V2QQof/EL/o1y2dQHumjSqexuYjmoG2bOK1EeIwA16MVS6x3Aups3rhC9PM+htFpaePkb4gGmrsMqCOug9WG0ZLNyW/LB40nkpmrzeO20HzBJxS/J7P3jbt8KHYWaHGdyYjd08iuFYPV1jQ9gfIjUWBnKmdMT9BX4UsY0V6gTv07f33+V/ooA1yLbksraaRr5je8u4ACsfXKpWHvEco3emEQ3Xl9dpkWsv4p2KEC/skrdt2P44z6sa4n7IBuaEDVJ3YBne3/A+soESK7GBWsN/mB2Z1x3EeCVubCQyhD31O92/ikCRGN0K3BML//win67n3VvhvI3eJcCZNhBn8OWNBTh+J22G96aCpKN/EYD3h8Q35X+WS/6lxzQij4lOQQL3Rvt62U62Br
    username: AgBTm5yUoajeIHt2pR2lPEFFbZ5dhqFdp4PwWESA/Ztym1zRwYhequ/cLyayYKh5hU/IoopT905sGiYSMsh2P9G2NZEpTqOgFq9vIRdLgwdxGPTUh/qK301fEEodxsjdjl3Q/JgDaiLcpw/g3sN+77wOAuXpmLUXQXC8wDPndUJm6S4MGHrmgxJf4czLqWC4pL0d9KwSw0FAgdG24f+Qi+F7VTVDy2aLGBNbwzHle/FsG9E1XTuB9Xl0n/Ta89D8mwm3N6VBhImgA+MZ4u2bvrFrzV/1NtWDNA9yT1MqwO4gSkvc9/dE47MQy2K+YKs6cMbv1h1iE59o2jDWrnBuMqePiQCsHVBNjFu6E7x+oNwIPyBeJ2F5Y1rs4OF93XISrXsLDYFc+6hM7MDmdZ2bmIMBDmJPiaBLnOhmYGShcVQpb1G1TTR4PMPUnw3H+iMnKFJ0TpMd6qAGaUMcr7/z9DahvNzzB8tEECTM8KqJ1AXCo/Y1YrvCbh1k3NNGUVcszDoqRx4Yz8nRIzC6xU0WccA8aZh3PwcNSj8BOY7LUQez3ZzxcZW2qNxas92dysdr22fNsaBimSuyPfnRpevQlIXJpdZSkK+8iXDEE5p2YdqLMWw5BS1+/enID70Fy0QXSrhBLnXpsC9oUEB+fLLMjZSPMaIlijdrOVwwi/hS3KTqvf5KJrlV4s+azqh9fJoGNL5jpQYiVz9ZIRB7Ohvg
  template:
    metadata:
      name: homeassistant-ccu
      namespace: homeassistant
