enabled: true
existingSecret: gitea-actions-secret
existingSecretKey: token
giteaRootURL: https://gitea.reckeweg.io
statefulset:
  replicas: 1
  timezone: Europe/Berlin
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 4000m
      memory: 6Gi
  actRunner:
    registry: docker.io
    repository: gitea/act_runner
    tag: "0.6.1"
  dind:
    extraEnvs:
      - name: DOCKER_IPTABLES_LEGACY
        value: "1"
