---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ad-ldaps-pkcs12-password
  namespace: windows-ad
spec:
  encryptedData:
    password: AgBHthiWqRNH5cCQT1Pp/jFvrcwGEEim702OfbN+BdFpan1ajThMtY5TnRvXxN0t6Nvl9osy44BH+qNR8wonEHSnyfduNbLbEqQ97uZ3EIR6dG1BfZmrDN3uDAEdhaf9NG6YbKcBI2JBA47LcpmtpWQXsrP4je10qIYHQ1Kf50LN63u4NP9AV/j+TyVRqWLt0Tb46ptR5U+G7aIDheQ+EHFC8Hth0lEzjVges95fgXyqkhrwku4tFgOfEADPFpXRvjqgQKCmlE5X8vxO2ANd9aNAAD2iyxAwhlVfd6l9KwKsogvMCk9HuXAIuqx/Zp96J13t8M9vL9qyTU74xZH9oCUVXv8osNVXObjzHWhljm/9Ho4rMoaW2eH6qHYh2QWeMPXYxbCXlePzbxCCwyw8DrRJ3Saj9X4JwYfFL/mSU5ycq7aAUZe2cL2GUqRWtN3kPoDFwD6xvN3hiGIVimPziD5Bsd6pFpcIbs5PW6C6ZYweH+iyXjmmWAQLCVw3WObXZXKIIoFpdeLRxRoIDiyERiKpCrX2r4z82TNCl/Y6t5M7untzOGcwVH/59E1MfaQvgowLJKPYpCvLMDfuc+QgMKPaa7xt5o4LhX/DhLfKYVM9QHW6678kplAqPM+dbrJqfrLHh8gvEYJ33OBWqam3qmPVYDRcrOohdlpVji5wVnUmaqrRxtWYcDkOAEUyzTjFICBcJ75lbhRWLYg=
  template:
    metadata:
      name: ad-ldaps-pkcs12-password
      namespace: windows-ad
    type: Opaque
