---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ldap-service-credentials
  namespace: windows-ad
spec:
  encryptedData:
    password: AgA9m/ewvpmfdcTDx6uC5zW4MoTvdSUe6t40AsH0rrSINHcIbDk/U7zqOFczxyA82jBi8DnIvbkCEgdmmtxtihxrHvmUsMdy7GJ05wUkewd2C3kNyIMs33wl/3L2DCFf2aR80EjtNoHNDQ5HGtClta8fCiZUFLCva/0WAoGi3PJebX9290wz4GdlDss7JLvb20kPD7KYpt+BxezmI3VtwJUHvQMJZkIvzVUL9Hv5gqhqu3zh9QnikhXMQbGg3iXSSIoBFYEp6GrJN2fn4bM0dbeHEK+ZEbMabEbT2BMxbTRP2E5KhRaObSdhqi7MGTXlltZtXbsV36Kyc8htzc2rQppYnERhsspuakIsEmqIQ9fJv0CdblNGtaqFq33KwjTDmRCsiEmXrlm2GXHJtVjh/yBjUEzgIWtRK7xdvTU808CDIYKzb8GihRhMajyxMXUFl+R+fVG7vRh9GnkkgIugEAPy0gBDsvBzMnfeKWsyplpi/7pRx41XaDaPeCouB1cObeHiSA1es7hOBqzuOEnyHEkRwMTwdiGA76qOaSEJjRmFp2Oaq8nB2+1IE+FhVLuP1jqA6HIF5ueh1drZTFGcyNLxnnbmaEdFi55EFxE4Wdl6Us2s0tNbN1BotTLo7GaRhxwywCJvSBjjXOJmZS0PngVfXdvlUqY+OMfdgAZdLgAQKg3y6INajkaRofjDq1i3PZ/9J1nn/iPgh4g=
    username: AgCqZwtvbTimuRS0kWEU138uNDhSBhMmMPiyt4D83uOJ/oeO81QU9CEPss/ZOzM1Nj0xblbw6mqemz1aDrOuTGtjpTY4UiWAxlyw7Ws1iaNeYmRsNzG9k36m5Xw7J26ZNl0JfletInfCIUwuCOeguISYCGQV7W6BPt5l2yz0zUXGZTU2Li6pzKWmIokrDvY0+GzcFTOtP7u85tN+TVR2kvr/ZxUH8GoKlmolo1Add6PXrG4sgo0leWLFpvnPPa5zXCWXNBjhXcAGemVtzFO8m28kMXOBsag7/RSXlRUQghFxzTXawB/s4hWz91zcGXmj3p7cIfH6ppzirwcx4Yhug6ubOEiSMCKR1VahosHt5bqklLF0bbt7eHi09jxjsoA7/8Y0Riv07h0yiMMVmNBzvO4YPeqWeBe879/if+KNmT7GLUexYnnxXHbk3lMsrFNZGep34BiUdaDZXr/pAuzmfCBRHDbr6UqZ7ZKIPVjEFCsu/kN5VF2CqQy6j4i5LupIyE0GRemGYcXtPcPES1Q0gTUx21ige/uvjSgpEeWQTPiBYwJErboK9T+NZC71NABT0RJFxZeDvOoBq41US1wTQGk+fadSyYPcTsp+cDlK1spblK7VkLq4FgzGPAwPh/K+6JaMPPHRk1rsAvpjfTVThPZl6APUdO/W95RHqXiiduwmu40yoWrZS+MGv482DoTigeM5cMke7vVXu45tUNjpgdQ+XOUk17BgBI8MuP4PEXxbQLYA8w==
  template:
    metadata:
      name: ldap-service-credentials
      namespace: windows-ad
    type: Opaque
