---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ldap-service-credentials
  namespace: windows-ad
spec:
  encryptedData:
    password: AgCqLsky1GnEXeHyXY+Xp5jipIIdNwiuvZB8HQDrFZJvmBs5YqFi9UREgRHFn66ENdfMFvu8aA+1O6rEeXZkwJDkokR5xIV05WmyG8N0Tk3dKONxY6Pu6w7aSqiTIHpyLoYxh3x7OIQGBsrd9vwo0lLkhXCfkcN+6Slj9sJP7boEYtft2g9HgxJrFMrXACA36WUgAIjc0F6E6BP7J4uab3jDH8XbswZOLJ98CDxzw3snSIWxMeJc68nht0XnK9rblrha61mW3YZk1glMVcGrvG+osTrX9RsrRmPum78wPnVZgXXH8e/OXbBqBn1gS3H1zN8+1dtvWQfa1Vt2e9gAnae3m7olP9hbWxHeNBupX+tz1INNJ5rehgAx+sVslKlVZ3fPukIYODgQBeTxYpBfQLz9Vsv78JagANijvfrX1wg3sG75b5GyJSljoO3CS/vDFhzKok4ULbSRgCK97kXbvAiXeqJcWCSs1CNbXa9EZg/ZHX5FoLqOAIvEzoBYgs8QSaNP+aBckrtW0xUpHWtmagCtdOuGt9Ihamq+omKh92LBnkXahocNvd9pQ0fZ5VqqzE4Vrc8X/ICSJK8wsRTJJC7kF5Ur6N9wOoe3iJgnlKO1ylxlwCRXd4oNDW6XduGZF2hpi/6NZlgGE/Cy0Q0sHQ9j/yZUf8Pk/+VF2vXUPouM1FyWFupJ0cp8fIRvGmkIWCoG88sVTOTfnbE=
    username: AgBkJBPdMVHx5JZug+rQa7u68OF0F6/enxSkekz/O099jabqVnXyGEvI+cLUHzZhdcheM/mkSjn6TdyI2IprkZIAS2ipvW91gJqPovBjkaH/10uWVhrp/hTLFzvrr1tpTcFwJNofTZGHcQEpXYvXu1YyMknzSyBIJr4pq7Hheq9TDk3mABt0SjSGQF/tKjNGaZyGRQkXdS2gqX8mWzO47kRanDMMqQQF8PtzS9ujcvPonhOQM83S4tgKhEZ/J/Z92Ooxxq1KFVap24RklvdWHoKqJwKI5h4Em1e9kAHfvwEzt4I82gKA/TlcT12Bc6kvT/KJRyd2VusBeFSw60Gq1rFWCNqkkdP7efDAdeuuowfNdPU/1JFr4umyQqiFOtsGv9uRQ7PtyZ34UV9NS9G1NhcDIxV6cIGuWmzNUnP+hsNmvDahaiWbmuDg2VXC60PBQW4z6pWy3HwiVt7QHT0YOQ6XDBT+fhMZpHlUKSgBduHU+SSqiodOlA9MyHsl2EHNjMft2ZOKKXFch4iX+MFA6laK6C3cZscEWXy+X3WAJw9xwSki34/y+uGWoJ/LZQge2OoBYR8NcHUxYCrPXzDuSzOl0GaDCyGZggJkQle+//yEzBCjVUyOIhg0kgfdxPrXLf0ky1XjYCoyQIzZqOAwZZ/KDYmEuPTQtwk9VUA0sHcta2kaSr3BQe2HG2Alyi+eCu6WePEAyCo8BuKtpEI=
  template:
    metadata:
      name: ldap-service-credentials
      namespace: windows-ad
    type: Opaque
