---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ad-ldaps-pkcs12-password
  namespace: windows-ad
spec:
  encryptedData:
    password: AgCcIV5uNVDvUeTJRp533d2KVqvrL1COFIDcq6ZLhkIY+VWAbW+poInYkQ8XfQoTmpOw6azUQp6XJrKycgLUVo6bGmJ7gL7yq6PEAOKeg/ruiQyAAfXXMIdGHSmar1q6L+SdBIx6ObIZ/T2Ehs274XBlQinZY6yD/6nDWfco6Tkxwc28MwIvP7SnWQCZNPxlINFrjlYu4j/4Jjz5Ms0a1CWOfX2iExWl07p46g2SepZ4Tg0NPr6m3ewO7BhBxBD8ZY9b+BkC1VDe/poMdNhcFxfcGyRw9Lq28FmDtPVAJO9DKFkwhtkIeU7FejaQcyzqkTS7jbZer7wVyFwFj6JeUv5Ci22w+YrN1ebZ+lic8/CPIifgigmH1OU6U/vvr7ViwuVTM/Orqx+A9B2C3l/OYQ/abUMg+fU3GNmY0dAcxgDl/KvXESrbEWbUznEU9EeRlTEoE43xgZQHBaFAb4gS4NwLWgA4Uudh+KoCnRWkTLCRi3YHwlIfiL0Pz/wO4dA+ghW6QlHlUptBcidi5gYHY8K47vjdigi6tB6SMArPJNXgmQo6kKKeoeaVjYeFAE63zRHGsI2mC8YfrK+IUUj6HrRBE+tl4Cs0wDTtb8G1INLwnF/SOtVKlqkHATZzcFXh+F+Mxz2U3AydGxOpklq04fw7arJajC6Zw4RdeIzCqTWUq+8H91Q/A9vEF2m5iG3ShgYUOfLSxaEr0mc=
  template:
    metadata:
      name: ad-ldaps-pkcs12-password
      namespace: windows-ad
    type: Opaque
