---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ad-ldaps-pkcs12-password
  namespace: windows-ad
spec:
  encryptedData:
    password: AgAs/Wxc12hY1nEPyaKMfrwwECweCjYIc7VC15BiybFAn8iuZ+PbFtUuRw10kbKkrCnxKUjW9/+Ju1AEDglLPBVgIUwLo4FF54q7HhoeLw+ZDhxY/GCpaYZ2Ow45EGTGPvK1GVVCzjKqis0XoofaDUstqCL9KEaYeSToEAFn2PlvTs9YslGnQ5YgjA78eZa+x3ul1deuvHR+GBKprI6Jr2KdsxPyJSTulqeNZN9sy6w9+e1J6JGNA8L7OTZ6iXuqJUAAPjKyvB18dm01ZJG2IVKln2038tzKpSZFSPtrNp3HgmI/phcASZxL9DlO8S4YIkQSz+TioxYjcN1xppU1DX6gIm1q5tXEqhHWEg8Y0jfybPThg8E8t0kfrtiCPimm9pXZG8k3iIFRyQALlHbD+3DylIbl0fF/ch3P1AIKncDx4XNzGG5RzNtlm4o7Ktj6PeGyJll076ddCMko29l7+LTzZm7eVy3INKVI0RxSr1sj5KzFHaKlhyV/VYJFeM6urFvoZWF/Z/6cp1F1wthQ5dl+r484tzXf1cyvsVMZE2AgMtRHg1fhhkSW9utnGymsnz7mjEKz5RZa7JJTyRdIO3zDoOXJPsQE1kbK24l2dx2dL2vHUEs6Gj7N72j/FXgyLDhf7VWN2xhuhkm7wJKuYaf5WlTuloCaeISubqyoM+xX+iamfZWeaffGfyo/FQJIC+LbKgA3vGeMkVA=
  template:
    metadata:
      name: ad-ldaps-pkcs12-password
      namespace: windows-ad
    type: Opaque
