---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ldap-service-credentials
  namespace: windows-ad
spec:
  encryptedData:
    password: AgCqljBbw5wngR04UIUODFchQLoyX1uFEGTIjVkUwI8osLZQRTg7hcO57/nVx9d/BSg16hfoHzLNdE6nKyz9lD1TavCyAuQbPy1aauPiVWhiaS8geFxoAg4HigAaIVOlmCNePqcsoM6OsK3/TigZFSZnQWwus4GAvBzBxYxRy0HY6TGmHtlCZTiIAkbey84I8H+Ez6WfnhjRclKo/mQcwBit0YSUi7Z5gxRvDvQMm3AO+nlrOE/TEYTMss/R2raI6F/Jd2+aXJB6JjUM1WPsGeToNV7xzOk8WJh+KcXgRhu85VVXeEYpEZUZiPjbfmHlE7medtAF8K+xwuG5JHr4LR1G/gHwgzIo2YfGbLa6ifwvRblxphii3odoTuVoZHjWkNVzaMzQMIPpm+44QYPo3mQwONuwId7bRtr8XRN9cxnmHrl+lvTTKWNghENjpTCoFT6kMYHP8ipRQgu4pw3BunpwXXXtEghttrwe6CRaSJxOn9DKMsMQEO6CxicVkNG4F+5u47cxwjYvjflVHF8CA9xuk1Eg+5YZFibVDRJuofi8gYZTeES1pH0Jsgcq5PFQoGegMnJia38ne9TBdPmlZ3pcQ4pMvRaBOryVQeYGxmezqiTTkvgWFUsnOKzdimW/s0BGMJv6UPZJgwVOFwuOdLL0I5gI4ZGMvaNR8Hg+xnVGQSf4g1iq9rz4kwWJ301r30oXs/CB7lfqDb8=
    username: AgCpRIa9Bu99h+N76JiWsb9y13pwPJWg+Bg2V39ZQ9wRsEwdwebr9g0xyr+E78VXNfxHliVzfsjiNJrr4S6z9PJrwVphe5PKVWIltYYweO5+cDoHXNCB24Pv68a8X/zcXpKqSc6i+bfHocONkqocLpeAM689+zy58QmyqJYcgPtkAccErKpkpr/SHt41C+tyRUCoH9hFXzgRrsferS6WCj++C3erCt4/LQZORenu1LwxPTDdsWrtcSfYyoAkkdmAg466Z1TBqp2Yy8+dW/QnYtVCPcxP6jlFpKLsgRZZjZG/bZTtserupfN/R0IExuyznK8qRuxnn/6VMYIgTwC3bYgY/asx6vDOuJzf31rWOzscIGe138qI6s+U7BOmNtRsuJRP7Ilay3CLESwG6BLDKP5Y8YgwnZ06U5sKvjoKWKWO64QbWFUkGMsEr4D0WavuTJBNCZyLEQizKHUdM+nqmKnlNbTggIOS88RCmzgUspZXylARVc2FzKsksQXTjquPi5Bc1LO4chxL2vRg19NIqU7mQtXBxGwvp811f54UOgEj36LkkzWqegIbVKK/3RnrJEhh80szZu7twIumJhSptocefaNk2YFkHTHKU0dZ2GSjFc2mYy33RTWZylwadWZLj79Ajr+TgddxnjJB8FqScLNPJG1jAbjv7Cj5qB2aPkwf26Qz7DBf7aER0b4qNIQ91rqzUPME6OQKHZBmfBM=
  template:
    metadata:
      name: ldap-service-credentials
      namespace: windows-ad
    type: Opaque
