---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-postgresql-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgApF288htpqIw18CjMQWmqwax3RiUO5yiEYvpUHSI2yQvBhItq7z2pLTUeGt/DEzvXsGxZrqJktO38r1Be9MwccXd3pKU107A9aRlGS7k50ZeYLFAeUqGfZ08qZlIfnb4lDx49Z6SNZTEBdtgZIiQhtCvhIGXDcYz5UsT3goC0xccSqceFIxba2WlGkL9J96bPL6YQ57n4dtQvBDzhG88lnN/jaH8sWSPvaXR1aFoBzvvSIrmmx7NzcE2e2MACXtWzo5xtiFMu3gmOaXfG6S8MKhW8J4vr1Z8Woj5oO7aKKcM4nMA3vw9Y27cyZsN4qXSFMtnORDmj0szWjewa/94/wvJrN7SKrQxUmcIw5y37cZw+29uUBg7Cw6WtcQfh/3Or7cdu3fa1wALlXd3SJ5+FAYc5IcPA2JzNoRDvmgmZgMwpf2Z1loCmcPDXP5l1seW169yHa3pmG6/Rtl639UtmBW2tnt1juNp4AadakKz+53m1q7E8/eRPQS5sfp0oiSmBFR/CNBf5c4ZVskGdTPb9cl9/iFT6yvOAHdkwcdpfXmYZ5ctE7DsMO+4piiIH9EjKzJuG1BoWP/c6zTa/J6WoAg2ul8eTHacdEw1K79j6DxEg9ZD0oaTh7PSAX6aygF+oOErBhSgdtXGSDSLPTfCzliCZ2nC42d1gwjf1Apff+u4fOywWnGmluHqIpDTsUnIiGJv7GGM24zP55hF9aOPtu
    postgres-password: AgCWd3Nwu1ow+5+BL4s/aoAZ0GIl6aZWed4ZiNPqs8xEMkT1vqt5PksxpEOR1MZlwxCPXsMCwK7/r6HFabhMohb+8N2cwZ5nw9Owi/mFjDz8PrKpgiEPGx/xqPEzfjhnwhwQLIBRDU59Sdm3dgQQr9F/3U91ReFwft0Ccjsd/0GLjnpiIGRC51W2oTZ/pnYXAP1+5aEdFZHh/2/tggdEsywRlxdnCnRF9WfPS59cBiAm7wYgXC3g+Mjl8yuLB5js9W7r66lXydjFnFbbwKCIQ3Oh1YUccxBcLHePdZSMUjdbhVJZ8we7gcC+iIShcWU6NLueu3x8Bn6cF75l84dvdZ617f5ZoA52c3Hv8Q4xXcH2NvU3WOVeY4i41+EgPfcJiWS10R7QDFu1IS2yUfEXGjs8hVFCQl91iyZPIJtEt6XwN7XNPtgaAqNiDNAZjOSVcSLR6q6ntd2Ab1TJHxJKG0ueGWdJHbhtJ5zDknlue+ii0TsMLMiGVY/7tzG/Xuz2tkv//292L+PNlS3W5vpAENAXLODMyCu0QR5AxWhii4q87hdmps63tTo63/7CkfXyOPZlkmyyzj2GYGk5WjSz1FJyrvN3hdHTjd1cNj6zIhOLk604vdceLvAzbftoiFhzs/z+50Rz47YG3CDRlvwDoa0HOpRs/e4BIWWMOsxciF1B2tMsU33VQIkOl0W5R7Ol+kOqRy9WTfTABLtpoEEVLwzx5HEK
  template:
    metadata:
      name: gitea-postgresql-secret
      namespace: gitea
    type: Opaque
