---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-postgresql-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBjE7jHZXQKhq2CXoKFP4vdnc78mahSm11B189+YuvF4RirHgXM260YiVYKYEBGz3JNVNzrm7oho4dHqAqUrDuyPad2EsLcdbrJQgAHhGcaRQKY+IWtKcW+To+ZGJpv5PKM2Mk5JPHO/z0WaRLiH6GEJcUIiV2n1XCdTYwPjS0tm2oAQaWZ3bXyoQiZDdJIcK8eckTwsYTQqfY6CqlqC1XWxElZ/7RttJSjZb9Di6OIBjVkYjjbmJxR8/i8+JJQ6OlOizAQpLSshG3iHIukHyq3VzCIIonom+xRe914h8Q+4e1bz3CUOsw244zAsmNYkRet7aEIvJjLieWF5BXJooOshOcjNXG2gGWOXj73hOPBp8hFf7alGMHQbLyECxMvgkfIhWHjmbQZheamzrsYvyrigf61BN6ZMgWdeepx3sfA9REabFJJW5wAMOI0AtxeoNQDt9G2Iusp3AKmlEtGdZPu06NUb5wLCKi5W5fMt0TeZ2FJFtGo5mf7euWKWpz6EFBdpDRYqAjOdbLgmQ/DmS/JHRFH6GZ1GUEBKniU9yPehc6fCnJqAqv2RnHiF93T3dkT/78/9J83/7+zRUCmUzj2bf0aXEwp+A+7Gq/sYUazVyCcgFudW1csyvWtNmasX0Q+kNOS7J/DxtOepK0P7XKUrxcAA0GSTVHXVFMPiguMmwKA/jgKrgSCKwPktnlHg71Lv1iPyfBgJ5VnKdsuRqde
    postgres-password: AgCioMdOr0JYu7MCkIykDN2kT/Hylp8h4PxOlQpaIDHSex6qZas0eGKyg+zce7BwpmoSByVOAat+LxwN+xLztEC+GztjqOE23ZBGkEeyHzCUs5U13dVrtlMXc6lejPu+2ExeIH1L4Y7fsP+2QcB88MbAJ3ULBgFzycQvMvXL4RQgW1KE4xRgT1d/Ebf8ghzibgrIWpwk1nyYVoQ4L+e2H5pZtuUihbxq8txZInAYEACx3RFh/9fxiYnnPenVwDvaxSTjCRF4M1RduCzg8RwcHOv9+WEBjdvaqSRD0d2CGo+U3RbHvf+JxRn5iSDSoROSGrfKxHTx82WKt7vg15NoLh5WA3vwyEmHT7qx/ekGxAidR3o0F9Afuzlv8MjpUWvAdbmcc6XTwun/AD6Q/i2CQZT9QQloyVgEvtxS9jJD1yPPWWF1WYVuZEaFU3XTj+CM6jaN4FfgxmPH8hTaLMQ+OrgvnFOW8UCe5LrKHUjRAUBVS/5oIqh8q6d5mvTn5lo8Wlj048kYPK43dLiNRBSdf1uaq2kXWa9byRYblW00B5KOqzd6JpRpPATS9KxPoB4ePOBNTTb4IMU5m+iwdkMBOBA0WySh2o7SW/fE+vI+Eqbd4Vh49RAeAi7KrwJQs6XZGIWGLGasNr8lnqSUOHAS3itlYVNAbvxZ1fEQfxpRK4+/Psr3VSM+ZTe25sZxde9op090l4Ma+IShJJENpINZVm1+d4zv
  template:
    metadata:
      name: gitea-postgresql-secret
      namespace: gitea
    type: Opaque
