---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-postgresql-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgA4cWsIwWJJPDQq3pjc1Prxs3YiISb2Rr4WPQGyq2puzpeIO3cTZsBONYnIon4DhpC9BlYWGZoyf4Jrv7dWr73+H1Ln/hSMdHCRfiZgHoYjh61WSJTs1AG5UaF8iBYDBlnzQFVgPn0J98TFBza3u0hKDTPrzlSSjAmdF2a0JkSiD59JlIpKrnWpXjp+jnJNDtuvP/cyFf8SKl/hxQ533JR+c5S4kxa9KzKpZeHWXaCSE7YEMRF7DPsbvlh0Q9qHY7ZZYGodKmAEjn88QJHGXe/UUYvkES43l9YHcjpmd3ayCjWe0OV3wTsVfKY3BuHvnKWX8JAaRGflvsAdQbfQd2UlBaWzgWugDe8HKbqI+A7GCBiW85jFcdXNV5foq/chsQ4+ErA8Jot1sH6e0pafneXk2l+9IyWC3Jvin4oqjDQQvoxgxwSb9dVBHwmvf84hvg/GO2+cEDAzTcw75gocWHqc3OCV0F1+VgmWy1w8PwCC2L/aKS/Q51Q7p+eTgaMN75KpgXz+4LjwGVf2Ek4eZli74nXL4J6wWTBlQp26Af93y+rLMLNUwG4pddrrNE2Ma5faIdMBNX0IJNl+r58709HcO1PwPJ1NlK5z4fw1QlWWr44AUZCwGp5J1nQN85Kh0Enjr8m7LJlOB0W/uIOITqMqF/ga6+lmSqa7uOzpNMDRldd5Lw2Sc4Imn9XbbfKuPVgo+SqFCgDv/lb8aKyuy/aI
    postgres-password: AgCA3KKFoNcjXM2a8+5cmTu0AkGOG2YxWDyLa6PZrCfl87cjZSi28QR3NqT4sN4AnHsUsD4j9dLxuODGAb5FvwTnMNJCzSRVxmr2N0DoYi46Z0tXtlzUq1J3ALygjXUL6oLuTEscGP0MNPdhVqG18k62yniIYDbUDNKnmQvFzHBFlTaBPaQbvJygLkNAtlmp08MjVYbsRamXG2prcaRDSYMntHVikR98HS7XJvIGu25qCDF4yp3ZDuoUYPoWxT1FlBCAP+ryAB0s1rkJW1ZT2xngQf35CJM5+c84rMgjub3GNRhvmOQR4TyaHifR5XCxbv4TfjeICB+TVmBnIrIQfc8TK2zNDOiKvyBMzHr/G9aTO+Kud4GK2VSuaXW62684SaL+EEyMXcvVz9tyfI1UNGqT+C0pT8itdUefopGFOIZPETYjEiDQ2ED/QtY8bQwkLJH7fm4/W434Jueq63w3FHHUBeD8CaqNseAFyouOgHRQ2ArsPrIXRufzPVehj6+vWnoeIJttxaOejsvd+TvRONvuJhX1k8EEHqaPLt3N2SRvOi8SICIhrlJtf599rFzY9g2eYhpTn6iEp6L7XwdU7iRzXMeEj3yLHI5W/jsk2MJJHxtH39Ozy2gf7P95oXoXC2rNXspoDQ7VXLSRCHxJu8bEbmI031r7F0uEggHBTkMcMm7GI75WCgTkxzujZtZB3mrvE+g2q5imqCnptIO0x4lsx+nW
  template:
    metadata:
      name: gitea-postgresql-secret
      namespace: gitea
    type: Opaque
