apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-actions
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: actions
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/gitops/config/gitea/actions-values.yaml
    - repoURL: git@git.reckeweg.io:achim/homelab-infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@git.reckeweg.io:achim/homelab-infrastructure.git
      targetRevision: HEAD
      path: gitops/config/gitea/actions
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

