apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole
  namespace: guacamole
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: guacamole-guacamole-redirect-root@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: guacamole.reckeweg.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guacamole
                port:
                  number: 80
  tls:
    - hosts:
        - guacamole.reckeweg.io
      secretName: guacamole-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: guacamole-redirect-root
  namespace: guacamole
spec:
  redirectRegex:
    regex: "^https://guacamole\\.reckeweg\\.io/?$"
    replacement: "https://guacamole.reckeweg.io/guacamole/"
    permanent: false

