apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - guacd.yaml
  - guacamole.yaml
  - ingressroute.yaml
  - sealed-db-secret.yaml
  # sealed-oidc-secret.yaml  # Phase 2: aktivieren sobald Keycloak deployed
