---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client_secret: AgAtsf/dCrNs7cuWeDqambS/bhNp9Jpw5mtG7MLqBhkcGRPNugmkjujC2ioDS+IAz7clW95MN+vtolQvOq/Cz0Lqwmhd4pkuVnO3nj8A9qlANzagOjNnujkMNVXdd2Jl7OdyyBcDiLIbeN1/fTknRx0TAu7IqpmUWr7Qr7NU9TxiYyr6Cax8dsXwp1bQdt+3vAJzoG1Ct0lMH2P/+PBXcdUi7/qHFsxD2WNdiaxQj1GAX2Ye+FAbXONMzczIKpI9aEcwtZcrMChTK4DMhQVHrK1TqIDIBttmS01q+LhW6gl+CE3YPhVU16jC6okUXj7yqfLjknJooI+YXi3gFUzsoN8ITDiF/7LMCq5xN52LQAjVpGlgxHu9WqVVafbRgUBKSOdlZqmUDX+ODnql9njuhIx4MpORtELzJ+YZQtQ9a7GddmeA++IlWOkVhA+uLhdFtx1PWI13HLQWNGZ4yJeo/eJBYNGwexpl4LugDXAX6T02vXvG9Nmu1BiHPETnBiDVtydmkhxyf85iKm6prUiZDj+P9hZ8H/x0EqbfXpUO7nk/5oFs8gY/t+loja+93JbXkaFtqZ+D96qaWbMmhMv4uLBM5fGTibbNJNNzG8jXfuNGJ5MxvRRDEahzOhYCmBfAp+6f7ayIIFUy6fXVQaiORqnIh8zFlflzPjpFi4D4v77cxgIapGv1kHwiQnYspzrsbU3BabTz5lpp2JW+JMsBwMtQws9n8pPd7nZGqArDrlOFZA/piAErpAbGWTPcV0xp49MfCKs2yyAxFRN8qtZkAkUp
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
      # Noetig, damit argocd-cm den Wert per $argocd-oidc-secret:client_secret
      # referenzieren kann - ArgoCD liest nur Secrets mit diesem Label ein.
      labels:
        app.kubernetes.io/part-of: argocd
