---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client_secret: AgBiFVTeZb7DgWY+DKO2UArPyJtjVkuHORO260F0LViMI32xyp102WjkTGXB5tIVhHfYzQINly1lO0IZ4jtlU4N/51UqpescouDk/Bwdd4owClvpVuGDjcHHnlrQJ+lFYL/Gil4cGK0PmuRzVa2bXO4kZo72tXIdgJROIZivPosCkFAg6Qel4aiIa6UuHwTEDRc9uvk6E/iDZVpbUM68PWwk2/ZW8oYy2PnyREPSSnF+AiKvvre6TgjCHLCBgVW7qobnU5TGQLKAEhy0n1VL3UkWQsh0xVb5OU3TRJ7OI313rR1nWWvmBsGL2xMDW6tBmbbrYZjFBCAULxt3C23DF6L0Kj7FWtPs2SXub0+EtCtUB3bb0+qEjgntmKvNubS1Mn6lCgR6LYkviemoZ3fzIH4MI+eGig1N7bl26yo+vId8Yw5pQa363/U4e14N/jK6Ag93K4E0H5kWXcQu6tlTlNi6ob9HfSXTK/NfjV8XbYBRj8gg/e4E2c+5dvolA9rX/HnzAGATQciQGUEFyx+GCEV7qKAuHVDnmnv1xJgahskjvqwlbjgTyDbCIE1jYH0rweYeDuNwDXqVCkTrnqPwCNfCPjPMqtcbzNyVDy+JHwO24yLMRns/fWT1A5A+OyVHOhIH1GDFORw9W+Gh2voaSU0fWDnq+QJ1qVEBRwr0v9Y13o15J5rgT0w0Up+PeaETBh9iqOY3SP0DorpFygpAz1Jw574b4mgyqKW9gXTapi/knMGwd+XKI1oVJi56Fti/i3aqzdJNFq+IevJE4JtCr3mJ
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
